<#
    EmbedShaders.ps1

    Build step for the plain-HLSL shaders (the ones converted from Effects,
    each a Foo.hlsl plus Foo.effect.json). For every *.effect.json under
    -ShaderDir it compiles each entry point the manifest lists with fxc, then
    writes one C++ file holding the manifests and the bytecode as byte arrays.
    GraphicsDX11's fxEmbeddedShaders.cpp includes that file.

    Called from GraphicsDX11.vcxproj (target EmbedPlainShaders) before
    compiling. Written for Windows PowerShell 5.1.
#>
param(
    [Parameter(Mandatory = $true)][string]$ShaderDir,
    [Parameter(Mandatory = $true)][string]$OutFile,
    [string]$Fxc = ""
)

$ErrorActionPreference = "Stop"

function Find-Fxc([string]$hint) {
    if ($hint -and (Test-Path $hint)) { return $hint }
    $kits = Join-Path ${env:ProgramFiles(x86)} "Windows Kits\10\bin"
    $found = Get-ChildItem -Path $kits -Filter fxc.exe -Recurse -ErrorAction SilentlyContinue |
        Where-Object { $_.Directory.Name -eq "x64" } |
        Sort-Object FullName -Descending | Select-Object -First 1
    if (-not $found) { throw "fxc.exe not found (looked for '$hint' and under $kits)" }
    return $found.FullName
}

# C++ initializer list for a byte array, 32 bytes per line.
function Format-Bytes([byte[]]$bytes) {
    $sb = New-Object System.Text.StringBuilder
    for ($i = 0; $i -lt $bytes.Length; $i += 32) {
        $n = [Math]::Min(32, $bytes.Length - $i)
        $hex = [BitConverter]::ToString($bytes, $i, $n)
        [void]$sb.Append("`t0x").Append($hex.Replace("-", ",0x")).Append(",`r`n")
    }
    return $sb.ToString()
}

function Stage-Entries($stages) {
    foreach ($p in $stages.PSObject.Properties) {
        if ($null -ne $p.Value) { $p.Value }
    }
}

$fxcExe = Find-Fxc $Fxc
$ShaderDir = (Resolve-Path $ShaderDir).Path
$tmp = [IO.Path]::GetTempFileName()

$out = New-Object System.Text.StringBuilder
[void]$out.Append("// Generated by EmbedShaders.ps1 from the *.effect.json files under`r`n")
[void]$out.Append("// LibXLT/GraphicsDX11/Eff/private/Shaders. Do not edit.`r`n`r`n")
[void]$out.Append("namespace`r`n{`r`n")

$effects = @()
$shaderRoot = (Resolve-Path $ShaderDir).Path
$manifests = Get-ChildItem -Path $ShaderDir -Filter *.effect.json -Recurse | Sort-Object FullName
$e = 0
try {
    foreach ($file in $manifests) {
        $text = [IO.File]::ReadAllText($file.FullName)
        $manifest = $text | ConvertFrom-Json
        $hlsl = Join-Path $file.DirectoryName $manifest.hlsl
        $prefix = "k_e$e"

        # the manifest, NUL-terminated
        $jsonBytes = [Text.Encoding]::UTF8.GetBytes($text) + [byte]0
        [void]$out.Append("const unsigned char ${prefix}_manifest[] = {`r`n").Append((Format-Bytes $jsonBytes)).Append("};`r`n")

        # one bytecode blob per unique entry point + profile
        $seen = @{}
        $table = @()
        foreach ($tech in $manifest.techniques) {
            foreach ($pass in $tech.passes) {
                foreach ($stage in (Stage-Entries $pass.stages)) {
                    $key = "$($stage.entry)|$($stage.profile)"
                    if ($seen.ContainsKey($key)) { continue }
                    $seen[$key] = $true

                    # fxc writes warnings to stderr; with "Stop", PowerShell 5.1
                    # would turn those into a terminating error
                    $ErrorActionPreference = "Continue"
                    $log = & $fxcExe /nologo /T $stage.profile /E $stage.entry /Fo $tmp $hlsl 2>&1
                    $ErrorActionPreference = "Stop"
                    if ($LASTEXITCODE -ne 0) {
                        $log | ForEach-Object { Write-Host $_ }
                        throw "fxc failed: $($stage.entry) ($($stage.profile)) in $hlsl"
                    }
                    $name = "${prefix}_s$($table.Count)"
                    [void]$out.Append("const unsigned char ${name}[] = {`r`n").Append((Format-Bytes ([IO.File]::ReadAllBytes($tmp)))).Append("};`r`n")
                    $table += "`t{ `"$($stage.entry)`", `"$($stage.profile)`", $name, sizeof($name) },"
                }
            }
        }
        [void]$out.Append("const fxEmbeddedBytecode ${prefix}_bytecode[] = {`r`n").Append(($table -join "`r`n")).Append("`r`n};`r`n`r`n")

        # looked up by effect name: Special/Blur.effect.json is "Blur"
        $effectName = $file.Name -replace '\.effect\.json$', ''
        $source = $file.FullName.Substring($shaderRoot.Length).TrimStart('\', '/') -replace '\\', '/'
        $effects += "`t{ `"$effectName`", `"$source`", (const char*)${prefix}_manifest, ${prefix}_bytecode, $($table.Count) },"
        $e++
    }
}
finally {
    Remove-Item $tmp -ErrorAction SilentlyContinue
}

[void]$out.Append("}`r`n`r`n")
if ($effects.Count -gt 0) {
    [void]$out.Append("const fxEmbeddedEffect fxEmbeddedShaders::k_Effects[] = {`r`n").Append(($effects -join "`r`n")).Append("`r`n};`r`n")
} else {
    [void]$out.Append("const fxEmbeddedEffect fxEmbeddedShaders::k_Effects[] = { { nullptr, nullptr, nullptr, nullptr, 0 } };`r`n")
}
[void]$out.Append("const int fxEmbeddedShaders::k_NumEffects = $($effects.Count);`r`n")

$dir = Split-Path $OutFile -Parent
if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir | Out-Null }
[IO.File]::WriteAllText($OutFile, $out.ToString())
Write-Host "EmbedShaders: $($effects.Count) effect(s) -> $OutFile"
