/******************************************************************************
 * Copyright 1986-2009 by mental images GmbH, Fasanenstr. 81, D-10623 Berlin,
 * Germany. All rights reserved.
 ******************************************************************************/

#include <mentalmill_compiler.h>

#ifndef GEN_MSL_PLUG_H
#define GEN_MSL_PLUG_H 1

namespace MI { 

namespace GEN_MSL {

using namespace MSDK;

//! mslCodeGenerator_plugin implements the plugin.
class mslCodeGenerator_plugin : public ICode_generator12_plugin
{

private:

    //! The code generator of this plugin.
    ICode_generator *m_code_generator;

protected:

    //! The destructor.
    ~mslCodeGenerator_plugin();

public:

    //! The constructor.
    mslCodeGenerator_plugin();

    //! Get the name of the plugin.
    /*!
     *  \returns    The name of the plugin.
     */
    virtual const char *get_name() const;

    //! Get the type of the plugin.
    /*!
     *  \returns    The type of the plugin.
     */
    virtual const char *get_type() const;

    //! Get the version of the plugin.
    /*!
     *  \returns    The version of the plugin.
     */
    virtual int get_version() const;

    //! Get the compiler used to compile the plugin.
    /*!
     *  \returns    The compiler used to compile the plugin.
     */
    const char *get_compiler() const;

    //! Release the plugin giving back all allocated resources.
    void release();

    //! The language that this code generator plugin generates.
    /*!
     *  \returns    The language generated by this plugin.
     */
    const char* get_language_name();

    //! Indicates whether the plugin generates hardware or software shaders.
    /*!
     *  \returns    The type of shader generated by this plugin.
     */
    Code_type get_code_type();

    //! Get the code generator.
    /*!
     *  \returns    The code generator of this plugin.
     */
    ICode_generator *get_code_generator();

};

}

}

#endif
