/*****************************************************************************
**	mslGeneratedShader.hpp
**
**	 mslGeneratedShader implements MentalMill's IGenerated_shader
** to generate our DirectX 11 shader code from a syntax tree.
**
**	StudioGPU
**	Copyright(C) 2010 - All Rights Reserved
\****************************************************************************/

#ifdef MSL_GENERATEDSHADER_HPP
#error mslGeneratedShader.hpp multiply included
#endif
#define MSL_GENERATEDSHADER_HPP

#ifndef MSL_DEFS_HPP
#include "mslDefs.hpp"
#endif

#include <string>


//============================================================================
//! mslGeneratedShader implements the shaders generated by this plugin.
//============================================================================
class mslGeneratedShader : public IGenerated_shader
{
public:

    //! The constructor.
    mslGeneratedShader();

    //! The destructor.
    virtual ~mslGeneratedShader();

    //! Increment the reference count.
    void reference();
    
    //! Decrement the reference count.
    void release();
    
    //! Get an interface from this interface.
    /*!
     *  \param  interface_id    The identifier of the interface to get.
     */
    Interface *get_interface(int interface_id);

    //! Get the identifier of the object which is the target of this interface.
    /*!
     *  \returns    The identifier of the object which is the target of
     *              this interface.
     */
    Uint64 get_interface_target() const;

    //! Get the language of the generated shader.
    /*!
     *  \returns    The language of the generated shader.
     */
    const char *get_language() const;
    
    //! Get the number of source code buffers.
    /*!
     *  \returns    The number of source code buffers.
     */
    int get_source_code_count() const;

    //! Get the output extension of a source code buffer.
    /*!
     *  \param  index   The index of the source code buffer.
     *  \returns        The output extension of the source code buffers.
     */
    const char *get_source_code_ext(int index) const;

    //! Get the size of a source code buffer.
    /*!
     *  \param  index   The index of the source code buffer.
     *  \returns        The size of the source code buffers.
     */
    int get_source_code_size(int index) const;

    //! Get the contents of the a source code buffer.
    /*!
     *  \param  index       The index of the source code buffer.
     *  \param  out_buffer  The output buffer.
     *  \param  buffer_size The size of the output buffer.
     */
    void get_source_code(int index,char *out_buffer,int buffer_size) const;

    //! Print code to the code string.
    /*!
     *  \param  code    A printf-style format string.
     *  \param  args    A variable length argument list.
     */
    void print_code(const char *code,va_list args);

    //! Print code to the code string.
    /*!
     *  \param  code    A printf-style format string.
     */
    void print_code(const char *code,...);

    //! Append string to the code string.
    /*!
     *  \param  i_String   String to add to code string.
     */
	void append_string(const std::string& i_String);

    //! Print tabs to the code string.
    /*!
     *  \param  tabs    The number of tabs to print.
     */
    void print_tabs(int tabs);

private:

    //! The reference count.
    int m_ref_count;

    //! The code string.
    std::string m_code;
};

