/*****************************************************************************
**	mslVisitorHLSL.cpp
**
**	 see .hpp
**
**	StudioGPU
**	Copyright(C) 2010 - All Rights Reserved
\****************************************************************************/
#include "mslVisitorHLSL.hpp"
#include "mslGeneratedShader.hpp"
#include "mslHeaderFooter.hpp"
#include "mslQualifiedName.hpp"
#include "mslVersionNumber.hpp"

#include "Core/dbg/dbgMsg.hpp"

#include <stdarg.h>

namespace
{
}

mslVisitorHLSL::mslVisitorHLSL(ILog *log,mslGeneratedShader *shader)
    : m_log(log)
    , m_shader(shader)
{
}

void mslVisitorHLSL::print_code(const char *code,...)
{
    va_list args;
    va_start(args,code);
    m_shader->print_code(code,args);
    va_end(args);
}

void mslVisitorHLSL::print_tabs(int tabs)
{
    m_shader->print_tabs(tabs);
}

void mslVisitorHLSL::begin_shader_file()
{
	print_code("/*** This code was generated by gen_sgpu %s ***/\n", GENSGPU_DLLVERSION);

	//std::string header;
	//mslHeaderFooter::DecryptHeader(header);
	//m_shader->append_string(header);
}

void mslVisitorHLSL::end_shader_file()
{
	//std::string footer;
	//mslHeaderFooter::DecryptFooter(footer);
	//m_shader->append_string(footer);

    print_code("\n/*** end of file ***/\n");
}

void mslVisitorHLSL::begin_compilation_unit()
{
    //print_code("\n/*** begin compilation unit ***/\n");
}

void mslVisitorHLSL::end_compilation_unit()
{
    //print_code("\n/*** end compilation unit ***/\n");
}

void mslVisitorHLSL::begin_import(const char *file_name)
{
    print_code("/*** import \"%s\" ***/\n",file_name);
}

void mslVisitorHLSL::end_import()
{
    print_code("\n/*** end of import ***/\n");
}

void mslVisitorHLSL::begin_shader(
    const mslQualifiedName *superclass,
    const char *name)
{
    //if(superclass)
    //    print_code("shader %s : %s {\n",name,superclass->c_str());
    //else
    //    print_code("shader %s {\n",name);
}

void mslVisitorHLSL::end_shader()
{
    //print_code("}");
}

void mslVisitorHLSL::begin_brdf(
    const mslQualifiedName *superclass,
    const char *name)
{
    //if(superclass)
    //    print_code("brdf %s : %s {\n",name,superclass->c_str());
    //else
    //    print_code("brdf %s {\n",name);
}

void mslVisitorHLSL::end_brdf()
{
    //print_code("}");
}

void mslVisitorHLSL::begin_technique(
    const mslQualifiedName *superclass,
    const char *name)
{
    //if(superclass)
    //    print_code("technique %s : %s {\n",name,superclass->c_str());
    //else
    //    print_code("technique %s {\n",name);
}

void mslVisitorHLSL::end_technique()
{
   // print_code("}");
}

void mslVisitorHLSL::begin_inputs()
{
    print_code("\n/*** Shader Constants from MetaSL ***/\n");
}

void mslVisitorHLSL::end_inputs()
{
    print_code("\n");
}

void mslVisitorHLSL::begin_outputs()
{
    print_code("\noutput:\n");
}

void mslVisitorHLSL::end_outputs()
{
    print_code("\n");
}

void mslVisitorHLSL::begin_members()
{
	//HLSL doesn't use members section
    //print_code("\nmember:\n");
}

void mslVisitorHLSL::end_members()
{
   // print_code("\n");
}

void mslVisitorHLSL::begin_declaration(int depth)
{
    print_code("\n");
    print_tabs(depth);
}

void mslVisitorHLSL::end_declaration(int depth)
{
    print_code(";");
    if(!depth)
        print_code("\n");
}

void mslVisitorHLSL::begin_definition(int depth)
{
    print_code("\n\n");
    print_tabs(depth);
}

void mslVisitorHLSL::end_definition(int depth)
{
    print_code("\n");
}

void mslVisitorHLSL::variable_declaration(
    const char *storage,
    const mslQualifiedName *type,
    const char *name,
    const char *dimension)
{
    if(storage)
        print_code("%s ",storage);
    for(int i = 0; i < type->size(); i++) {
        if(i)
            print_code("__");
        print_code("%s",(*type)[i]);
    }
    print_code(" %s",name);
    if(dimension)
        print_code("[%s]",dimension);
}

void mslVisitorHLSL::begin_function_declaration(
    const mslQualifiedName *type,
    const char *name)
{
    for(int i = 0; i < type->size(); i++) {
        if(i)
            print_code("__");
        print_code("%s",(*type)[i]);
    }
    //print_code(" %s(",name);
	//bga - always have state and light data in our functions?
    print_code(" %s(State state, Light_iterator light",name);
}

void mslVisitorHLSL::end_function_declaration()
{
    print_code(")");
}

void mslVisitorHLSL::begin_initializer(int depth)
{
    print_code(" = ");
}

void mslVisitorHLSL::begin_constructor_declaration(	
    const char *name,
    bool is_static)
{
    if(is_static)
        print_code("static ");
    print_code("%s()",name);
}

void mslVisitorHLSL::end_constructor_declaration()
{
}

void mslVisitorHLSL::begin_destructor_declaration(	
    const char *name,
    bool is_static)
{
    if(is_static)
        print_code("static ");
    print_code("~%s()",name);
}

void mslVisitorHLSL::end_destructor_declaration()
{
}

void mslVisitorHLSL::end_initializer(int depth)
{
}

void mslVisitorHLSL::parameter_declaration(
    int position,
    const char *mode,
    const mslQualifiedName *type,
    const char *name,
    const char *dimension)
{
    if(position)
	{
        print_code(",");
		// each parameter on a new line
		print_code("\n");
		print_tabs(1);
	}
    if(mode)
        print_code("%s ",mode);
    for(int i = 0; i < type->size(); i++) {
        if(i)
            print_code("__");
        print_code("%s",(*type)[i]);
    }
    print_code(" %s",name);
    if(dimension)
        print_code("[%s]",dimension);
}

void mslVisitorHLSL::begin_block(int depth)
{
    print_code("\n");
    print_tabs(depth);
    print_code("{");
}

void mslVisitorHLSL::end_block(int depth)
{
    print_code("\n");
    print_tabs(depth);
    print_code("}");
}

void mslVisitorHLSL::begin_expression_statement(int depth)
{
    print_code("\n");
    print_tabs(depth);
}

void mslVisitorHLSL::end_expression_statement(int depth)
{
    print_code(";");
}

void mslVisitorHLSL::bool_literal(const char *value)
{
    print_code("%s",value);
}

void mslVisitorHLSL::int_literal(const char *value)
{
    print_code("%s",value);
}

void mslVisitorHLSL::scalar_literal(const char *value)
{
    print_code("%s",value);
}

void mslVisitorHLSL::string_literal(const char *value)
{
    print_code("\"%s\"",value);
}

void mslVisitorHLSL::begin_array_literal(int depth)
{
    print_code("{ ");
}

void mslVisitorHLSL::begin_array_literal_item(int depth,int position)
{
    if(position)
        print_code(", ");
}

void mslVisitorHLSL::end_array_literal_item(int depth,int position)
{
}

void mslVisitorHLSL::end_array_literal(int depth)
{
    print_code(" }");
}

void mslVisitorHLSL::var_ref(mslQualifiedName *name,const IDeclaration *declaration)
{
	//bga - Have to give some sort of prefix to input variables
	// because they become global inputs. Using "sgpu_" for now, but maybe use "g_"?
	if (declaration && declaration->is_input())
		print_code("sgpu_");

    for(int i = 0; i < name->size(); i++) {
        if(i)
            print_code("__");
        print_code("%s",(*name)[i]);
    }
}

void mslVisitorHLSL::state_var_ref(
        const char *name,
        const IDeclaration *declaration)
{
	//bga - not all state variables can be references as "state." Some with have
	// to resolve to HLSL functions?
    //print_code("%s",name);
    print_code("state.%s",name);
}

void mslVisitorHLSL::type(const char *name)
{
    print_code("%s",name);
}

void mslVisitorHLSL::begin_enum(int depth,mslQualifiedName *name)
{
    print_code("enum ");
    for(int i = 0; i < name->size(); i++) {
        if(i)
            print_code("__");
        print_code("%s",(*name)[i]);
    }
    print_code(" { ");
}

void mslVisitorHLSL::enum_value(int position,mslQualifiedName *name)
{
    if(position)
        print_code(", ");
    for(int i = 0; i < name->size(); i++) {
        if(i)
            print_code("__");
        print_code("%s",(*name)[i]);
    }
}

void mslVisitorHLSL::enum_value(int position,mslQualifiedName *name,int value)
{
    if(position)
        print_code(", ");
    for(int i = 0; i < name->size(); i++) {
        if(i)
            print_code("__");
        print_code("%s",(*name)[i]);
    }
    print_code(" = %d",value);
}

void mslVisitorHLSL::end_enum(int depth)
{
    print_code(" }");
}

void mslVisitorHLSL::begin_struct(int depth,mslQualifiedName *name)
{
    print_code("struct ");
    for(int i = 0; i < name->size(); i++) {
        if(i)
            print_code("__");
        print_code("%s",(*name)[i]);
    }
    print_code(" {");
}

void mslVisitorHLSL::end_struct(int depth)
{
    print_code("\n");
    print_tabs(depth);
    print_code("}");
}

void mslVisitorHLSL::begin_field(int depth,const char *name)
{
}

void mslVisitorHLSL::end_field(int depth,const char *name)
{
    print_code(" %s",name);
}

void mslVisitorHLSL::begin_expression_list()
{
    print_code("(");
}

void mslVisitorHLSL::begin_expression_list_item(int position)
{
    if(position)
        print_code(",");
}

void mslVisitorHLSL::end_expression_list_item(int position)
{
}

void mslVisitorHLSL::end_expression_list()
{
    print_code(")");
}

void mslVisitorHLSL::begin_conditional_expression()
{
    print_code("(");
}

void mslVisitorHLSL::begin_conditional_condition()
{
    print_code("(");
}

void mslVisitorHLSL::end_conditional_condition()
{
    print_code(")");
}

void mslVisitorHLSL::begin_conditional_then()
{
    print_code(" ? (");
}

void mslVisitorHLSL::end_conditional_then()
{
    print_code(")");
}

void mslVisitorHLSL::begin_conditional_else()
{
    print_code(" : (");
}

void mslVisitorHLSL::end_conditional_else()
{
    print_code(")");
}

void mslVisitorHLSL::end_conditional_expression()
{
    print_code(")");
}

void mslVisitorHLSL::op(IType *type,const char *name)
{
    if(!strcmp(name,"."))
        print_code(".");
    else if(!strcmp(name,"[]"))
        print_code("[");
    else
        print_code(" %s ",name);
}

void mslVisitorHLSL::begin_pre_op(
    IType *type,const char *name,bool parentheses)
{
    if(parentheses)
        print_code("(");
    print_code("%s",name);
}

void mslVisitorHLSL::end_pre_op(
    IType *type,const char *name,bool parentheses)
{
    if(parentheses)
        print_code(")");
}

void mslVisitorHLSL::begin_post_op(
    IType *type,const char *name,bool parentheses)
{
    if(parentheses)
        print_code("(");
}

void mslVisitorHLSL::end_post_op(
    IType *type,const char *name,bool parentheses)
{
    print_code("%s",name);
    if(parentheses)
        print_code(")");
}

void mslVisitorHLSL::begin_bin_op(
    IType *type,const char *name,bool parentheses)
{
    if(strcmp(name,"[]") && parentheses)
        print_code("(");
}

void mslVisitorHLSL::end_bin_op(
    IType *type,const char *name,bool parentheses)
{
    if(strcmp(name,"[]")) {
        if(parentheses)
            print_code(")");
    } else {
        print_code("]");
    }
}

void mslVisitorHLSL::begin_cast(const mslQualifiedName *type)
{
    print_code("%s(",type->c_str());
}

void mslVisitorHLSL::end_cast(const mslQualifiedName *type)
{
    print_code(")");
}

void mslVisitorHLSL::begin_call(const mslQualifiedName *name,
                            const IDeclaration *declaration,
							bool i_bRequiresState)
{
    for(int i = 0; i < name->size(); i++) {
        if(i)
            print_code("__");
        print_code("%s",(*name)[i]);
    }
    print_code("(");

	//bga - adding in state and light when calling one of the shader's methods.
	//if(declaration && (declaration->is_method())) {
	if (i_bRequiresState) {
		print_code("state,light");
	}
}

void mslVisitorHLSL::end_call()
{
    print_code(")");
}

void mslVisitorHLSL::begin_state_call(const mslQualifiedName *name,
                            const IDeclaration *declaration)
{
    print_code("%s(",name->c_str());
}

void mslVisitorHLSL::end_state_call()
{
    print_code(")");
}

void mslVisitorHLSL::begin_argument(int position)
{
    if(position)
        print_code(",");
}

void mslVisitorHLSL::end_argument(int position)
{
}

void mslVisitorHLSL::begin_if(int depth)
{
    print_code("\n");
    print_tabs(depth);
    print_code("if");
}

void mslVisitorHLSL::begin_if_condition()
{
    print_code("(");
}

void mslVisitorHLSL::end_if_condition()
{
    print_code(")");
}

void mslVisitorHLSL::begin_then(int depth)
{
}

void mslVisitorHLSL::end_then(int depth)
{
}

void mslVisitorHLSL::begin_else(int depth)
{
    print_code("\n");
    print_tabs(depth);
    print_code("else");
}

void mslVisitorHLSL::end_else(int depth)
{
}

void mslVisitorHLSL::end_if(int depth)
{
}

void mslVisitorHLSL::begin_switch(int depth)
{
    print_code("\n");
    print_tabs(depth);
    print_code("switch");
}

void mslVisitorHLSL::begin_switch_selector()
{
    print_code("(");
}

void mslVisitorHLSL::end_switch_selector()
{
    print_code(") {");
}

void mslVisitorHLSL::begin_case_label(int depth)
{
    print_code("\n");
    print_tabs(depth);
    print_code("case ");
}

void mslVisitorHLSL::end_case_label(int depth)
{
    print_code(":");
}

void mslVisitorHLSL::default_label(int depth)
{
    print_code("\n");
    print_tabs(depth);
    print_code("default:");
}

void mslVisitorHLSL::end_switch(int depth)
{
    print_code("\n");
    print_tabs(depth);
    print_code("}");
}

void mslVisitorHLSL::begin_while(int depth)
{
    print_code("\n");
    print_tabs(depth);
    print_code("while");
}

void mslVisitorHLSL::begin_while_condition(int depth)
{
    print_code("(");
}

void mslVisitorHLSL::end_while_condition(int depth)
{
    print_code(")");
}

void mslVisitorHLSL::end_while(int depth)
{
}

void mslVisitorHLSL::begin_do_while(int depth)
{
    print_code("\n");
    print_tabs(depth);
    print_code("do");
}

void mslVisitorHLSL::begin_do_while_condition(int depth)
{
    print_code("\n");
    print_tabs(depth);
    print_code("while(");
}

void mslVisitorHLSL::end_do_while_condition(int depth)
{
    print_code(")");
}

void mslVisitorHLSL::end_do_while(int depth)
{
    print_code(";");
}

void mslVisitorHLSL::begin_for(int depth)
{
    print_code("\n");
    print_tabs(depth);
    print_code("for");
}

void mslVisitorHLSL::begin_for_init()
{
    print_code("(");
}

void mslVisitorHLSL::end_for_init()
{
    print_code(";");
}

void mslVisitorHLSL::begin_for_condition()
{
}

void mslVisitorHLSL::end_for_condition()
{
    print_code(";");
}

void mslVisitorHLSL::begin_for_update()
{
}

void mslVisitorHLSL::end_for_update()
{
    print_code(")");
}

void mslVisitorHLSL::end_for(int depth)
{
}

void mslVisitorHLSL::begin_foreach(int depth)
{
    print_code("\n");
    print_tabs(depth);

	//bga - commenting out the foreach to flatten the light loop,
	// will need to handle other kinds of foreach loops also later.
    print_code("//foreach");
    //print_code("foreach");
}

void mslVisitorHLSL::begin_foreach_iterator()
{
    print_code("(");
}

void mslVisitorHLSL::end_foreach_iterator()
{
    print_code(")");
}

void mslVisitorHLSL::end_foreach(int depth)
{
}

void mslVisitorHLSL::break_statement(int depth)
{
    print_code("\n");
    print_tabs(depth);
    print_code("break;");
}

void mslVisitorHLSL::continue_statement(int depth)
{
    print_code("\n");
    print_tabs(depth);
    print_code("continue;");
}

void mslVisitorHLSL::begin_return_statement(int depth)
{
    print_code("\n");
    print_tabs(depth);
    print_code("return ");
}

void mslVisitorHLSL::end_return_statement(int depth)
{
    print_code(";");
}

void mslVisitorHLSL::begin_annotation(int depth)
{
    print_code("\n");
    print_tabs(depth);
    print_code("<");
}

void mslVisitorHLSL::end_annotation(int depth)
{
    print_code("\n");
    print_tabs(depth);
    print_code(">");
}
