/******************************************************************************
 * The following code was generated by the mental mill(R)                     *
 * Fx_code_generator build 45261.42172 05 Jun 2009 nt-x86-64
 *                                                                            *
 * Copyright (c) 1986-2009 mental images GmbH, Berlin, Germany. *
 * All rights reserved.                                              *
 ******************************************************************************/

//
// The state structure is used internally within the fragment shader to
// commonly used values.
//
struct State
{
	float4 tex_coord[4];
	float3 position;
	float3 origin;
	float3 normal;
	float3 direction;
	float ray_length;
	float3x3 tangent_space[1];
};

//
// Values for the light_type parameter of light shaders
//
#define LIGHT_POINT    0
#define LIGHT_SPOT     1
#define LIGHT_INFINITE 2
#define LIGHT_PLANAR   3

//
// The light iterator structure holds the return values resulting from
// evaluating a light.
//
#ifndef __LIGHT_ITERATOR_STRUCT
#define __LIGHT_ITERATOR_STRUCT
struct Light_iterator {
    float3 msl_point;
    float4 msl_contribution;
    float4 msl_raw_contribution;
    float  msl_dot_nl;
    float3 msl_direction;
    float  msl_distance;
    float4 msl_shadow;
    int    msl_count;
};
#endif // __LIGHT_ITERATOR_STRUCT

struct Ray {
    float3 msl_origin;
    float3 msl_direction;
};

Ray __Ray_ctor(float3 o, float3 d)
{
    Ray r;
    r.msl_origin = o;
    r.msl_direction = d;
    return r;
}

float2 __float2_ctor(float v)
{
	return v.xx;
}

float3 __float3_ctor(float v)
{
	return v.xxx;
}

float4 __float4_ctor(float v)
{
	return v.xxxx;
}

void __make_basis(const float3 n, const float3 u, const float3 v,
        out float3 t, out float3 b)
{
    b = normalize(cross(u,n));
    t = cross(n,b);
    if (dot(b,v) < 0.0)  b = -b;
}

float3 __perspective_divide(float4 pt)
{
    return pt.xyz/pt.w;
}

// 
// State dependant variable recalculation. 
// 
void __update_state_origin_or_position(inout State state) 
{ 
    state.direction = state.position - state.origin; 
    state.ray_length = length(state.direction); 
    state.direction = normalize(state.direction); 
} 

//
// The following are free parameters of the shader that should be set by the
// application at runtime.
//
float4 msl_point_light_color
<
	string UIName = "Color";
	string UIWidget = "Color";
> = float4(1.0, 1.0, 1.0, 1.0);
float msl_point_light_intensity
<
	string UIName = "Intensity";
	float UIMin = 0.0;
	float UIMax = 10.000000;
	float UIStep = 0.01;
	string UIWidget = "slider";
> = 3.141593;
float msl_point_light_distance_falloff_exponent
<
	string UIName = "Distance Falloff Exponent";
	float UIMin = 0.0;
	float UIMax = 4.000000;
	float UIStep = 0.01;
	string UIWidget = "slider";
> = 0.0;
float msl_point_light_distance_scale
<
	string UIName = "Distance Scale";
	float UIMin = 0.001000;
	float UIMax = 2.000000;
	float UIStep = 0.01;
	string UIWidget = "slider";
> = 1.0;
texture __msl_diffuse_tex_texture <
	string UIName = "msl_diffuse_tex_texture";
	string ResourceName = "default.dds";
	string ResourceType = "2D";
>;

sampler2D msl_diffuse_tex_texture = sampler_state {
	Texture = <__msl_diffuse_tex_texture>;
	MinFilter = Linear;
	MagFilter = Linear;
	MipFilter = Linear;
};

texture __msl_norm_tex_texture <
	string UIName = "msl_norm_tex_texture";
	string ResourceName = "unfiltered_noise_normal.dds";
	string ResourceType = "2D";
>;

sampler2D msl_norm_tex_texture = sampler_state {
	Texture = <__msl_norm_tex_texture>;
	MinFilter = Linear;
	MagFilter = Linear;
	MipFilter = Linear;
};

float msl_norm_transf_amount
<
	string UIName = "Amount";
	float UIMin = -1.000000;
	float UIMax = 1.0;
	float UIStep = 0.01;
	string UIWidget = "slider";
> = 1.0;
float msl_phong_illum_diffuse_scalar
<
	string UIName = "Diffuse Float";
	float UIMin = 0.0;
	float UIMax = 1.0;
	float UIStep = 0.01;
	string UIWidget = "slider";
> = 0.700000;
float4 msl_phong_illum_specular_color
<
	string UIName = "Specular Color";
	float4 UIMin = float4(0.0, 0.0, 0.0, 0.0);
	float4 UIMax = float4(1.0, 1.0, 1.0, 1.0);
	float UIStep = 0.01;
	string UIWidget = "slider";
> = float4(1.0, 1.0, 1.0, 1.0);
float msl_phong_illum_specular_scalar
<
	string UIName = "Specular Float";
	float UIMin = 0.0;
	float UIMax = 1.0;
	float UIStep = 0.01;
	string UIWidget = "slider";
> = 0.060000;
float msl_phong_illum_specular_shininess
<
	string UIName = "Specular Shininess";
	float UIMin = 0.0;
	float UIMax = 100.000000;
	float UIStep = 0.01;
	string UIWidget = "slider";
> = 15.000000;
float3 msl_light0_position : Position 
<
	string Object = "PointLight0";
	string Space = "View";
> = float3(0.0, 0.0, 0.0);
float4x4 msl_light0_transform_internal_to_light;
float4x4 msl_light0_transform_light_to_internal;
texture __msl_cube_env_env_tex <
	string UIName = "msl_cube_env_env_tex";
	string ResourceName = "default_reflection_cubic.dds";
	string ResourceType = "Cube";
>;

samplerCUBE msl_cube_env_env_tex = sampler_state {
	Texture = <__msl_cube_env_env_tex>;
	MinFilter = Linear;
	MagFilter = Linear;
	MipFilter = Linear;
	AddressU = Clamp;
	AddressV = Clamp;
	AddressW = Clamp;
};

float msl_cube_env_intensity
<
	string UIName = "Intensity";
	float UIMin = 0.0;
	float UIMax = 10.000000;
	float UIStep = 0.01;
	string UIWidget = "slider";
> = 1.0;


//
// The following are parameters representing non-varying state variables 
// referenced by the shader. These should be set by the application at runtime.
// Note that vector parameters should be provided in camera space.
//
float4x4 __object_to_ndc : WorldViewProjection
<
	string UIWidget = "none";
>;
float __refracted_ior = 1.01;
float __incident_ior = 1.0;
float4x4 __object_to_camera : WorldView
<
	string UIWidget = "none";
>;
float4x4 __camera_to_world : ViewInverse
<
	string UIWidget = "none";
>;
float4x4 __camera_to_object : WorldViewInverse
<
	string UIWidget = "none";
>;
float4 __scene_ambient : Ambient
<
	string UIName = "Scene Ambient";
	string UIWidget = "color";
> = float4(0.0, 0.0, 0.0, 1.0);
//                                                   
// The following are parameters representing non-varying non-state variables      
// referenced by the shader. These should be set by the application at runtime.             
//                                                   
float4x4 __internal_to_light;
float4x4 __light_to_internal;


#ifndef mi_phong_specular__float__float3__float3__float3__float
#define mi_phong_specular__float__float3__float3__float3__float 1
float mi_phong_specular(
	inout State state,
	float3 msl_lightDir,
	float3 msl_eyeDir,
	float3 msl_n,
	float msl_specular_shininess)
{
	float3 msl_refl = ((2.f * (-(dot(msl_eyeDir, msl_n)))) * msl_n) + msl_eyeDir;
	float msl_h = dot(msl_refl, msl_lightDir);
	return ((pow((max(msl_h, 0.f)), msl_specular_shininess)) * (msl_specular_shininess + 2.f)) / (2.0 * 3.14159265358979323846f);
}
#endif



//
// The App2vert structure defines the vertex attributes used by the vertex
// shader. The application should supply a vertex stream containing these 
// elements.
//
struct App2vert
{
	float3 position : POSITION;
	float3 normal : NORMAL;
	float4 texcoord0 : TEXCOORD0;
	float4 texcoord1 : TEXCOORD1;
	float4 texcoord2 : TEXCOORD2;
	float4 texcoord3 : TEXCOORD3;
	float3 tex_du : TANGENT;
	float3 tex_dv : BINORMAL;
};

//
// The Vert2frag_out structure defines values output by the vertex shader.
//
struct Vert2frag_out
{
	float4 hpos : POSITION;
	float4 tex_coord[4] : TEXCOORD0;
	float3 tex_du : TEXCOORD4;
	float3 tex_dv : TEXCOORD5;
	float3 position : TEXCOORD6;
	float3 normal : TEXCOORD7;
};

//
// The Vert2frag_in structure defines values used by the fragment shader.
//
struct Vert2frag_in
{
	float4 hpos : POSITION;
	float4 tex_coord[4] : TEXCOORD0;
	float3 tex_du : TEXCOORD4;
	float3 tex_dv : TEXCOORD5;
	float3 position : TEXCOORD6;
	float3 normal : TEXCOORD7;
};

//
// This function is the main method of the vertex shader.
//
Vert2frag_out vertex_main(
	App2vert vs_in)
{
	Vert2frag_out vs_out;
	float4 position = float4(vs_in.position, 1);
	vs_out.hpos = mul(position, __object_to_ndc);
	vs_out.position = mul(position, __object_to_camera).xyz;
	vs_out.normal = mul((float3x3)__camera_to_object, vs_in.normal);
	vs_out.tex_coord[0] = vs_in.texcoord0;
	vs_out.tex_coord[1] = vs_in.texcoord1;
	vs_out.tex_coord[2] = vs_in.texcoord2;
	vs_out.tex_coord[3] = vs_in.texcoord3;
	vs_out.tex_du = mul(vs_in.tex_du, (float3x3)__object_to_camera);
	vs_out.tex_dv = mul(vs_in.tex_dv, (float3x3)__object_to_camera);
	return vs_out;
}

//
// The following functions are generated from the MetaSL implementation of
// the shaders that are part of the compiled shader graph.
//

void Texture_lookup_2d_main(
	inout State state,
	sampler2D msl_texture,
	int msl_texture_space,
	float2 msl_texture_uv,
	out float4 msl_result)
{
	{
		msl_result = (tex2D(msl_texture, msl_texture_uv));
	}
}

void Normals_make_normal_main(
	inout State state,
	float4 msl_color,
	float msl_amount,
	out float3 msl_result)
{
	{
		float3 msl_n = (msl_color.xyz - 0.5) * 2.0;
		msl_n.xy *= msl_amount;
		msl_result = (normalize((mul((state.tangent_space)[0], msl_n))));
	}
}

void Light_point_main(
	inout State state,
	float4 msl_color,
	float msl_intensity,
	float msl_distance_falloff_exponent,
	float msl_distance_scale,
	out float4 msl_result,
	out float4 msl_light_shadow,
	inout float4x4 msl__state_transform_internal_to_light,
	inout float msl__state_light_distance,
	inout float4x4 msl__state_transform_light_to_internal)
{
	{
		float msl_attenuation = 1.0;
		if (msl_distance_falloff_exponent > (float(0)))
		{
			msl_attenuation = (pow((msl__state_light_distance * msl_distance_scale), (-msl_distance_falloff_exponent)));
		}
		msl_result = (float4((((float4(msl_color)) * msl_intensity) * msl_attenuation)));
		msl_light_shadow = (float4(1,1,1,1));
	}
}

void point_light_lightmain(
	inout State state,
	in float3 msl__state_light_position,
	in float4x4 msl__state_transform_internal_to_light,
	in float4x4 msl__state_transform_light_to_internal,
	out Light_iterator msl___light)
{
	float3 msl__state_light_to_surface = (state.position) - msl__state_light_position;
	float msl__state_light_distance = length(msl__state_light_to_surface);
	msl__state_light_to_surface /= msl__state_light_distance;
	float msl__state_light_dot_nl = dot((-msl__state_light_to_surface), (state.normal));
	float4 msl_point_light_result;
	float4 msl_point_light_light_shadow;
	Light_point_main(state, msl_point_light_color, msl_point_light_intensity, msl_point_light_distance_falloff_exponent, msl_point_light_distance_scale, msl_point_light_result, msl_point_light_light_shadow, msl__state_transform_internal_to_light, msl__state_light_distance, msl__state_transform_light_to_internal);
	msl___light.msl_point = msl__state_light_position;
	msl___light.msl_direction = (-msl__state_light_to_surface);
	msl___light.msl_distance = msl__state_light_distance;
	msl___light.msl_dot_nl = msl__state_light_dot_nl;
	msl___light.msl_raw_contribution = msl_point_light_result;
	msl___light.msl_contribution = msl_point_light_result;
	msl___light.msl_shadow = msl_point_light_light_shadow;
	msl___light.msl_count = 1;
}

void Illumination_phong_main(
	inout State state,
	float4 msl_diffuse_color,
	float msl_diffuse_scalar,
	float4 msl_specular_color,
	float msl_specular_scalar,
	float msl_specular_shininess,
	out float4 msl_result,
	out float4 msl_sum,
	out float4 msl_diffuse,
	out float4 msl_specular)
{
	{
		msl_diffuse = (float4(0.0, 0.0, 0.0, 0.0));
		msl_specular = (float4(0.0, 0.0, 0.0, 0.0));
		float4 msl_Rd = float4(((float4(msl_diffuse_color)) * msl_diffuse_scalar));
		float4 msl_Rs = float4(((float4(msl_specular_color)) * msl_specular_scalar));
		float4 msl_temp = float4(((float4(msl_Rd)) + (float4(msl_Rs))));
		float msl_maxc = max((max(msl_temp.r, msl_temp.g)), msl_temp.b);
		if (msl_maxc > 1.0)
		{
			msl_Rd /= msl_maxc;
			msl_Rs /= msl_maxc;
		}
		float3 msl_vdir = state.direction;
		Light_iterator msl_light;
		{
			point_light_lightmain(state, msl_light0_position, msl_light0_transform_internal_to_light, msl_light0_transform_light_to_internal, msl_light);
			{
				float msl_cos = saturate(msl_light.msl_dot_nl);
				if (msl_cos > 0.0)
				{
					msl_diffuse += (float4(((msl_cos / 3.14159265358979323846f) * (float4(msl_light.msl_contribution)))));
					float msl_s = mi_phong_specular(state, msl_light.msl_direction, msl_vdir, (state.normal), msl_specular_shininess);
					msl_specular += (float4(((msl_s * msl_cos) * (float4(msl_light.msl_contribution)))));
				}
			}
		}
		msl_diffuse *= msl_Rd;
		msl_specular *= msl_Rs;
		
		;
		msl_diffuse += (float4((((float4(msl_Rd)) / 3.14159265358979323846f) * (float4((__scene_ambient))))));
		msl_diffuse.a = 1.0;
		msl_specular.a = 1.0;
		msl_sum = (float4(((float4(msl_diffuse)) + (float4(msl_specular)))));
		msl_result = msl_sum;
	}
}

//
// The following method is the root function of the shader graph
//
float4 phong_illum_eval(State state)
{
	float4 msl_result;
	float4 msl_sum;
	float4 msl_diffuse;
	float4 msl_specular;
	float4 msl_diffuse_tex_result;
	Texture_lookup_2d_main(state, msl_diffuse_tex_texture, 0, (float2((state.tex_coord)[0].x, (state.tex_coord)[0].y)), msl_diffuse_tex_result);
	float4 msl_norm_tex_result;
	Texture_lookup_2d_main(state, msl_norm_tex_texture, 0, (float2((state.tex_coord)[0].x, (state.tex_coord)[0].y)), msl_norm_tex_result);
	float3 msl_norm_transf_result;
	Normals_make_normal_main(state, msl_norm_tex_result, msl_norm_transf_amount, msl_norm_transf_result);
	{
		float3 msl__normal_temp = state.normal;
		(state.normal) = msl_norm_transf_result;
		Illumination_phong_main(state, msl_diffuse_tex_result, msl_phong_illum_diffuse_scalar, msl_phong_illum_specular_color, msl_phong_illum_specular_scalar, msl_phong_illum_specular_shininess, msl_result, msl_sum, msl_diffuse, msl_specular);
		(state.normal) = msl__normal_temp;
	}
	return msl_result;
}

//
// This function is the main method of the fragment shader. It initializes the
// values in the state structure that are used by nodes in the shader graph
// and produces the final result of the shader.
//
float4 fragment_main(
	Vert2frag_in fs_in) : COLOR
{
	State state;
	state.position = fs_in.position;
	state.normal = normalize(fs_in.normal);
	state.tex_coord = fs_in.tex_coord;
	state.origin = 0;
	state.ray_length = length(state.position);
	state.direction = state.position/state.ray_length;
	float3 t_tex_tangent, t_tex_binormal;
	__make_basis(state.normal, fs_in.tex_du, fs_in.tex_dv, t_tex_tangent, t_tex_binormal);
	state.tangent_space[0] = transpose(float3x3(
	    t_tex_tangent,
	    t_tex_binormal,
	    state.normal));
	return phong_illum_eval(state);
}

//
// The following define the default technique and pass of the effect.
//
technique T0
{
	pass P0
	{
		VertexShader = compile vs_3_0 vertex_main();
		PixelShader  = compile ps_3_0 fragment_main();
	}
}

