/*** This code was generated by gen_sgpu ***/

/*** Shader Constants from MetaSL ***/

texture2D sgpu_diffuse_tex_texture
<
	string SasUiLabel = "diffuse_tex_texture";
	string SasUiControl = "FilePicker";
	string UiCategory = "MetaSL";
	string SasUiDescription = "Input from custom shader.";
	string name = "default.dds";
>;

float sgpu_phong_illum_diffuse_scalar
<
	string SasUiLabel = "Diffuse Float";
	string SasUiControl = "Slider";
	string UiCategory = "MetaSL";
	string SasUiDescription = "Input from custom shader.";
> = 0.700000;



void Illumination_sgpu_main(State state, Light_iterator light,
	float4 diffuse_color,
	float diffuse_scalar,
	out float4 result,
	out float4 diffuse)
{
	{
		diffuse = float4(0.0,0.0,0.0,0.0);
		float4 Rd = __color_ctor(float4(diffuse_color) * diffuse_scalar);
		float4 temp = Rd;
		float maxc = max(max(temp.r,temp.g),temp.b);
		if(maxc > 1.0)
			{
				Rd /= maxc;
			}
		//Light_iterator light;
		//foreach(light)
			{
				float cos = saturate(light.dot_nl);
				if(cos > 0.0)
					{
						diffuse += __color_ctor((cos / 3.14159265358979323846f) * float4(light.contribution));
					}
			}
		diffuse *= Rd;
		diffuse.a = 1.0;
		result = diffuse;
	}
}


void Texture_lookup_2d_main(State state, Light_iterator light,
	texture2D msl_texture,
	int texture_space,
	float2 texture_uv,
	out float4 result)
{
	{
		result = msl_tex2D(msl_texture,texture_uv);
	}
}


float4 sgpu_shader_main(State state, Light_iterator light)
{
	float4 result;
	float4 diffuse;
	float4 diffuse_tex_result;
	Texture_lookup_2d_main(state,light,sgpu_diffuse_tex_texture,0,float2(state.texture_coordinate[0].x,state.texture_coordinate[0].y),diffuse_tex_result);
	Illumination_sgpu_main(state,light,diffuse_tex_result,sgpu_phong_illum_diffuse_scalar,result,diffuse);
	return result;
}

/*** end of file ***/
