/*****************************************************************************
**	mslCompiler.cpp
**
**	 see .hpp
**
**	StudioGPU
**	Copyright(C) 2010 - All Rights Reserved
\****************************************************************************/
#include "mslCompiler.hpp"
#include "mslErrors.hpp"

#include "Core/dbg/dbgMsg.hpp"

namespace
{
	// Get shader string from IGenerated_shader
	void extract_shader_code(IGenerated_shader *i_Shader,
							 std::string & o_ShaderString,
							 int i_SourceIndex = 0,
							 const char *pFilename = NULL)
	{
		int size = i_Shader->get_source_code_size(i_SourceIndex);
		if (size) {
			char *buffer = buffer = new char[size];
			i_Shader->get_source_code(0, buffer, size);
			o_ShaderString = buffer;

			//bga - no longer writing shader to files for debugging
			//if (pFilename)
			//{
			//	// Temporary code that writes shader to disk.
			//	FILE *file = fopen(pFilename, "wt");
			//	if (file)  {
			//		fwrite (buffer, 1, size-1, file);
			//		fclose(file);
			//	}
			//}

			delete[] buffer;
		}
	}
	
	//int get_shader_index(
	//		const ICompilation_unit *comp_unit,
	//		const char *name)
	//{
	//	int shader_index = -1;
	//	if(name && name[0]) {
	//		// use the named shader class
	//		for(int i = 0; i < comp_unit->get_shader_count(); i++) {
	//			const char *shader_name = comp_unit->get_shader_name(i);
	//			if(!strcmp(shader_name, name)) {
	//				shader_index = i;
	//				break;
	//			}
	//		}
	//	} else {
	//		// use the first shader class
	//		shader_index = 0;
	//	}
	//	return shader_index;
	//}

}

//--------------------------------------------------------------------
// Compile
//--------------------------------------------------------------------
bool  mslCompiler::Compile(const std::string & i_ShaderName,
						   IMill_compiler *i_pMillCompiler,
						   IGraph_library *i_pGraphLibrary,
						   std::string &o_ShaderString,
						   std::string &o_MetaSLString)
{
	ICompiler_options *options;	// options for compilation of the shader graph
	ICompilation_unit *cunit;	// compilation unit of the shader graph
	IGenerated_shader *shader;	// shader generated by mental mill

	// Compile the Shader Graph, part one: Create compiler options
	options = i_pMillCompiler->create_options();

	// Compile the Shader Graph, part two: Specify the shader source and type
	//std::string full_shader_name = i_ShaderName + "_surface";	// have to add "_surface" in MM 1.2?
	//DBG_LOG("Shader name: " << full_shader_name);
	//options->set("shader_name", full_shader_name.c_str()); 
	DBG_LOG("Shader name: " << i_ShaderName);
	options->set("shader_name", i_ShaderName.c_str()); 
	options->set("shader_type", "surface");

	// Compile the Shader Graph, part three: Specify the sub-shaders for
	// the surface shader
	//options->set("environment", "cube_env");
	//options->set("lights", "point_light");

	// Receives error messages
    ICompiler_errors *errors = i_pMillCompiler->create_errors();

	// Compile the Shader Graph, part four: Get the compilation unit
	// by compiling the group specified above
	cunit = i_pMillCompiler->compile_group(i_pGraphLibrary, errors, options);
	if (!cunit) { 
		mslErrors::ReportErrors("Failed to compile shader graph", errors);
	    return false;
	}

	//DBG_LOG("Shader count: " << cunit->get_shader_count());
 //   const char *shader_name = options->get("shader_name");
 //   int shader_index = get_shader_index(cunit,shader_name);
	//DBG_LOG("Shader index: " << shader_index);


	// Generate an HLSL FX shader
	options->set("format", "HLSL");
	options->set("vertex_shader_profile", "vs_3_0");
	options->set("fragment_shader_profile", "ps_3_0");
	options->set("generate_samplers", "true");
	options->set("generate_umapped_annotations", "false");
	options->set("vs_binding_tangent", "TANGENT");
	options->set("vs_binding_binormal", "BINORMAL");
	options->set("flip_tex2d_v", "false");
	//shader = cunit->generate_shader("FX", options);
	shader = cunit->generate_shader("sgpu", options);
	int count = 0;
	if(!shader) {
		DBG_ERROR("Unable to generate an HLSL FX shader.");
		return false;
	} else {
		count = shader->get_source_code_count();
	}
	if (count != 1) {
		DBG_ERROR("Error: expected one source fragment for HLSL FX.");
		return false;
	}

	// Get out the shader: The FX back-end generates a single source
	// code string, so the procedure is to grab the first source code
	// string, get the size and allocate a buffer to hold it.
	if (count == 1) {
		extract_shader_code(shader, o_ShaderString, 0, "./sgpu_export.fx");
	}

	// Also compile a single MetaSL shader compiled from the 
	// nodes into a single shader. For this we use the "gen_msl.dll" backend 
	// that shipped with the Mental Mill Integrator Edition SDK.
	IGenerated_shader *msl_shader;	// shader generated by mental mill
	msl_shader = cunit->generate_shader("msl", options);
	if (!msl_shader) {
		DBG_ERROR("Unable to generate a single MetaSL shader from node graph.");
	} 
	else 
	{
		if (msl_shader->get_source_code_count() > 0)
		{
			extract_shader_code(msl_shader, o_MetaSLString, 0, "./sgpu_export.msl");
		}
	}

	// This organization is taken from the sample code, but it needs to 
	// be organized so that "false" return values above handle the releases also.
	options->release(); options = NULL;    
	cunit->release(); cunit = NULL;
	shader->release(); shader = NULL;
	if (msl_shader) msl_shader->release(); msl_shader = NULL;

	//bga - do we have to release the errors object also?

	return true;
}

