#if 0
//
// FX Version: fx_5_0
//
// 1 local buffer(s)
//
cbuffer $Globals
{
    float4  g_vTessellationFactor;      // Offset:    0, size:   16
    float4x4 g_world : World;           // Offset:   16, size:   64
    float4x4 g_vp : ViewProjection;     // Offset:   80, size:   64
    float4x4 g_wvp : WorldViewProjection;// Offset:  144, size:   64
    float4x4 g_uvTransform = { 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1 };// Offset:  208, size:   64
    float   g_glowSize = 0;             // Offset:  272, size:    4
    float   g_bumpMapScale : BumpMapScale = 1;// Offset:  276, size:    4
}

//
// 1 groups(s)
//
fxgroup
{
    //
    // 1 technique(s)
    //
    technique11 Default
    {
        pass PDefault
        {
            VertexShader = asm {
                //
                // Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.16384
                //
                //
                // Buffer Definitions: 
                //
                // cbuffer $Globals
                // {
                //
                //   float4 g_vTessellationFactor;      // Offset:    0 Size:    16 [unused]
                //   float4x4 g_world;                  // Offset:   16 Size:    64 [unused]
                //   float4x4 g_vp;                     // Offset:   80 Size:    64 [unused]
                //   float4x4 g_wvp;                    // Offset:  144 Size:    64
                //   float4x4 g_uvTransform;            // Offset:  208 Size:    64 [unused]
                //      = 0x3f800000 0x00000000 0x00000000 0x00000000 
                //        0x00000000 0x3f800000 0x00000000 0x00000000 
                //        0x00000000 0x00000000 0x3f800000 0x00000000 
                //        0x00000000 0x00000000 0x00000000 0x3f800000 
                //   float g_glowSize;                  // Offset:  272 Size:     4
                //      = 0x00000000 
                //   float g_bumpMapScale;              // Offset:  276 Size:     4 [unused]
                //      = 0x3f800000 
                //
                // }
                //
                //
                // Resource Bindings:
                //
                // Name                                 Type  Format         Dim Slot Elements
                // ------------------------------ ---------- ------- ----------- ---- --------
                // $Globals                          cbuffer      NA          NA    0        1
                //
                //
                //
                // Input signature:
                //
                // Name                 Index   Mask Register SysValue  Format   Used
                // -------------------- ----- ------ -------- -------- ------- ------
                // SV_POSITION              0   xyz         0     NONE   float   xyz 
                // NORMAL                   0   xyz         1     NONE   float   xyz 
                // TEXCOORD                 0   xy          2     NONE   float       
                // TANGENT                  0   xyz         3     NONE   float       
                // BINORMAL                 0   xyz         4     NONE   float       
                //
                //
                // Output signature:
                //
                // Name                 Index   Mask Register SysValue  Format   Used
                // -------------------- ----- ------ -------- -------- ------- ------
                // SV_POSITION              0   xyzw        0      POS   float   xyzw
                //
                vs_5_0
                dcl_globalFlags refactoringAllowed
                dcl_constantbuffer cb0[18], immediateIndexed
                dcl_input v0.xyz
                dcl_input v1.xyz
                dcl_output_siv o0.xyzw, position
                dcl_temps 2
                mad r0.xyz, v1.xyzx, cb0[17].xxxx, v0.xyzx
                mul r1.xyzw, r0.yyyy, cb0[10].xyzw
                mad r1.xyzw, cb0[9].xyzw, r0.xxxx, r1.xyzw
                mad r0.xyzw, cb0[11].xyzw, r0.zzzz, r1.xyzw
                add o0.xyzw, r0.xyzw, cb0[12].xyzw
                ret 
                // Approximately 6 instruction slots used
                            
            };
            PixelShader = asm {
                //
                // Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.16384
                //
                //
                //
                // Input signature:
                //
                // Name                 Index   Mask Register SysValue  Format   Used
                // -------------------- ----- ------ -------- -------- ------- ------
                // no Input
                //
                // Output signature:
                //
                // Name                 Index   Mask Register SysValue  Format   Used
                // -------------------- ----- ------ -------- -------- ------- ------
                // SV_TARGET                0   xyzw        0   TARGET   float   xyzw
                //
                ps_5_0
                dcl_globalFlags refactoringAllowed
                dcl_output o0.xyzw
                mov o0.xyzw, l(1.000000,1.000000,1.000000,1.000000)
                ret 
                // Approximately 2 instruction slots used
                            
            };
        }

        pass PTess
        {
            VertexShader = asm {
                //
                // Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.16384
                //
                //
                // Buffer Definitions: 
                //
                // cbuffer $Globals
                // {
                //
                //   float4 g_vTessellationFactor;      // Offset:    0 Size:    16 [unused]
                //   float4x4 g_world;                  // Offset:   16 Size:    64
                //   float4x4 g_vp;                     // Offset:   80 Size:    64 [unused]
                //   float4x4 g_wvp;                    // Offset:  144 Size:    64 [unused]
                //   float4x4 g_uvTransform;            // Offset:  208 Size:    64
                //      = 0x3f800000 0x00000000 0x00000000 0x00000000 
                //        0x00000000 0x3f800000 0x00000000 0x00000000 
                //        0x00000000 0x00000000 0x3f800000 0x00000000 
                //        0x00000000 0x00000000 0x00000000 0x3f800000 
                //   float g_glowSize;                  // Offset:  272 Size:     4
                //      = 0x00000000 
                //   float g_bumpMapScale;              // Offset:  276 Size:     4 [unused]
                //      = 0x3f800000 
                //
                // }
                //
                //
                // Resource Bindings:
                //
                // Name                                 Type  Format         Dim Slot Elements
                // ------------------------------ ---------- ------- ----------- ---- --------
                // $Globals                          cbuffer      NA          NA    0        1
                //
                //
                //
                // Input signature:
                //
                // Name                 Index   Mask Register SysValue  Format   Used
                // -------------------- ----- ------ -------- -------- ------- ------
                // SV_POSITION              0   xyz         0     NONE   float   xyz 
                // NORMAL                   0   xyz         1     NONE   float   xyz 
                // TEXCOORD                 0   xy          2     NONE   float   xy  
                // TANGENT                  0   xyz         3     NONE   float   xyz 
                // BINORMAL                 0   xyz         4     NONE   float   xyz 
                //
                //
                // Output signature:
                //
                // Name                 Index   Mask Register SysValue  Format   Used
                // -------------------- ----- ------ -------- -------- ------- ------
                // TEXCOORD                 0   xyzw        0     NONE   float   xyzw
                // TEXCOORD                 1   xyzw        1     NONE   float   xyzw
                // TEXCOORD                 2   xyz         2     NONE   float   xyz 
                // TEXCOORD                 3   xyz         3     NONE   float   xyz 
                // TEXCOORD                 4   xyz         4     NONE   float   xyz 
                // TEXCOORD                 5   xyz         5     NONE   float   xyz 
                // TEXCOORD                 6   xyz         6     NONE   float   xyz 
                //
                vs_5_0
                dcl_globalFlags refactoringAllowed
                dcl_constantbuffer cb0[18], immediateIndexed
                dcl_input v0.xyz
                dcl_input v1.xyz
                dcl_input v2.xy
                dcl_input v3.xyz
                dcl_input v4.xyz
                dcl_output o0.xyzw
                dcl_output o1.xyzw
                dcl_output o2.xyz
                dcl_output o3.xyz
                dcl_output o4.xyz
                dcl_output o5.xyz
                dcl_output o6.xyz
                dcl_temps 2
                mul r0.xyzw, v2.yyyy, cb0[14].xyzw
                mad o0.xyzw, cb0[13].xyzw, v2.xxxx, r0.xyzw
                mov o1.xy, v2.xyxx
                mov o1.zw, l(0,0,0,0)
                mad r0.xyz, v1.xyzx, cb0[17].xxxx, v0.xyzx
                mul r1.xyz, r0.yyyy, cb0[2].xyzx
                mad r0.xyw, cb0[1].xyxz, r0.xxxx, r1.xyxz
                mad r0.xyz, cb0[3].xyzx, r0.zzzz, r0.xywx
                add o2.xyz, r0.xyzx, cb0[4].xyzx
                mul r0.xyz, v3.yyyy, cb0[2].xyzx
                mad r0.xyz, cb0[1].xyzx, v3.xxxx, r0.xyzx
                mad o3.xyz, cb0[3].xyzx, v3.zzzz, r0.xyzx
                mul r0.xyz, v4.yyyy, cb0[2].xyzx
                mad r0.xyz, cb0[1].xyzx, v4.xxxx, r0.xyzx
                mad o4.xyz, cb0[3].xyzx, v4.zzzz, r0.xyzx
                mul r0.xyz, v1.yyyy, cb0[2].xyzx
                mad r0.xyz, cb0[1].xyzx, v1.xxxx, r0.xyzx
                mad o5.xyz, cb0[3].xyzx, v1.zzzz, r0.xyzx
                mov o6.xyz, v0.xyzx
                ret 
                // Approximately 20 instruction slots used
                            
            };
            HullShader = asm {
                //
                // Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.16384
                //
                //
                // Buffer Definitions: 
                //
                // cbuffer $Globals
                // {
                //
                //   float4 g_vTessellationFactor;      // Offset:    0 Size:    16
                //   float4x4 g_world;                  // Offset:   16 Size:    64 [unused]
                //   float4x4 g_vp;                     // Offset:   80 Size:    64 [unused]
                //   float4x4 g_wvp;                    // Offset:  144 Size:    64 [unused]
                //   float4x4 g_uvTransform;            // Offset:  208 Size:    64 [unused]
                //      = 0x3f800000 0x00000000 0x00000000 0x00000000 
                //        0x00000000 0x3f800000 0x00000000 0x00000000 
                //        0x00000000 0x00000000 0x3f800000 0x00000000 
                //        0x00000000 0x00000000 0x00000000 0x3f800000 
                //   float g_glowSize;                  // Offset:  272 Size:     4 [unused]
                //      = 0x00000000 
                //   float g_bumpMapScale;              // Offset:  276 Size:     4 [unused]
                //      = 0x3f800000 
                //
                // }
                //
                //
                // Resource Bindings:
                //
                // Name                                 Type  Format         Dim Slot Elements
                // ------------------------------ ---------- ------- ----------- ---- --------
                // $Globals                          cbuffer      NA          NA    0        1
                //
                //
                //
                // Patch Constant signature:
                //
                // Name                 Index   Mask Register SysValue  Format   Used
                // -------------------- ----- ------ -------- -------- ------- ------
                // SV_TessFactor            0   x           0  TRIEDGE   float   x   
                // SV_TessFactor            1   x           1  TRIEDGE   float   x   
                // SV_TessFactor            2   x           2  TRIEDGE   float   x   
                // SV_InsideTessFactor      0   x           3   TRIINT   float   x   
                //
                //
                // Input signature:
                //
                // Name                 Index   Mask Register SysValue  Format   Used
                // -------------------- ----- ------ -------- -------- ------- ------
                // TEXCOORD                 0   xyzw        0     NONE   float   xyzw
                // TEXCOORD                 1   xyzw        1     NONE   float   xyzw
                // TEXCOORD                 2   xyz         2     NONE   float   xyz 
                // TEXCOORD                 3   xyz         3     NONE   float   xyz 
                // TEXCOORD                 4   xyz         4     NONE   float   xyz 
                // TEXCOORD                 5   xyz         5     NONE   float   xyz 
                // TEXCOORD                 6   xyz         6     NONE   float   xyz 
                //
                //
                // Output signature:
                //
                // Name                 Index   Mask Register SysValue  Format   Used
                // -------------------- ----- ------ -------- -------- ------- ------
                // TEXCOORD                 0   xyzw        0     NONE   float   xyzw
                // TEXCOORD                 1   xyzw        1     NONE   float   xyzw
                // TEXCOORD                 2   xyz         2     NONE   float   xyz 
                // TEXCOORD                 3   xyz         3     NONE   float   xyz 
                // TEXCOORD                 4   xyz         4     NONE   float   xyz 
                // TEXCOORD                 5   xyz         5     NONE   float   xyz 
                // TEXCOORD                 6   xyz         6     NONE   float   xyz 
                //
                // Tessellation Domain   # of control points
                // -------------------- --------------------
                // Triangle                                3
                //
                // Tessellation Output Primitive  Partitioning Type 
                // ------------------------------ ------------------
                // Clockwise Triangles            Odd Fractional    
                //
                hs_5_0
                hs_decls 
                dcl_input_control_point_count 3
                dcl_output_control_point_count 3
                dcl_tessellator_domain domain_tri
                dcl_tessellator_partitioning partitioning_fractional_odd
                dcl_tessellator_output_primitive output_triangle_cw
                dcl_globalFlags refactoringAllowed
                dcl_constantbuffer cb0[1], immediateIndexed
                hs_fork_phase 
                dcl_hs_fork_phase_instance_count 3
                dcl_input vForkInstanceID
                dcl_output_siv o0.x, finalTriUeq0EdgeTessFactor
                dcl_output_siv o1.x, finalTriVeq0EdgeTessFactor
                dcl_output_siv o2.x, finalTriWeq0EdgeTessFactor
                dcl_temps 1
                dcl_indexrange o0.x 3
                mov r0.x, vForkInstanceID.x
                mov o[r0.x + 0].x, cb0[0].x
                ret 
                hs_fork_phase 
                dcl_output_siv o3.x, finalTriInsideTessFactor
                mov o3.x, cb0[0].y
                ret 
                // Approximately 5 instruction slots used
                            
            };
            DomainShader = asm {
                //
                // Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.16384
                //
                //
                // Buffer Definitions: 
                //
                // cbuffer $Globals
                // {
                //
                //   float4 g_vTessellationFactor;      // Offset:    0 Size:    16 [unused]
                //   float4x4 g_world;                  // Offset:   16 Size:    64 [unused]
                //   float4x4 g_vp;                     // Offset:   80 Size:    64 [unused]
                //   float4x4 g_wvp;                    // Offset:  144 Size:    64
                //   float4x4 g_uvTransform;            // Offset:  208 Size:    64 [unused]
                //      = 0x3f800000 0x00000000 0x00000000 0x00000000 
                //        0x00000000 0x3f800000 0x00000000 0x00000000 
                //        0x00000000 0x00000000 0x3f800000 0x00000000 
                //        0x00000000 0x00000000 0x00000000 0x3f800000 
                //   float g_glowSize;                  // Offset:  272 Size:     4 [unused]
                //      = 0x00000000 
                //   float g_bumpMapScale;              // Offset:  276 Size:     4 [unused]
                //      = 0x3f800000 
                //
                // }
                //
                //
                // Resource Bindings:
                //
                // Name                                 Type  Format         Dim Slot Elements
                // ------------------------------ ---------- ------- ----------- ---- --------
                // $Globals                          cbuffer      NA          NA    0        1
                //
                //
                //
                // Patch Constant signature:
                //
                // Name                 Index   Mask Register SysValue  Format   Used
                // -------------------- ----- ------ -------- -------- ------- ------
                // SV_TessFactor            0   x           0  TRIEDGE   float       
                // SV_TessFactor            1   x           1  TRIEDGE   float       
                // SV_TessFactor            2   x           2  TRIEDGE   float       
                // SV_InsideTessFactor      0   x           3   TRIINT   float       
                //
                //
                // Input signature:
                //
                // Name                 Index   Mask Register SysValue  Format   Used
                // -------------------- ----- ------ -------- -------- ------- ------
                // TEXCOORD                 0   xyzw        0     NONE   float   xyzw
                // TEXCOORD                 1   xyzw        1     NONE   float   xyzw
                // TEXCOORD                 2   xyz         2     NONE   float   xyz 
                // TEXCOORD                 3   xyz         3     NONE   float   xyz 
                // TEXCOORD                 4   xyz         4     NONE   float   xyz 
                // TEXCOORD                 5   xyz         5     NONE   float   xyz 
                // TEXCOORD                 6   xyz         6     NONE   float   xyz 
                //
                //
                // Output signature:
                //
                // Name                 Index   Mask Register SysValue  Format   Used
                // -------------------- ----- ------ -------- -------- ------- ------
                // TEXCOORD                 0   xyzw        0     NONE   float   xyzw
                // TEXCOORD                 1   xyzw        1     NONE   float   xyzw
                // TEXCOORD                 2   xyz         2     NONE   float   xyz 
                // TEXCOORD                 3   xyz         3     NONE   float   xyz 
                // TEXCOORD                 4   xyz         4     NONE   float   xyz 
                // TEXCOORD                 5   xyz         5     NONE   float   xyz 
                // SV_POSITION              0   xyzw        6      POS   float   xyzw
                //
                // Tessellation Domain   # of control points
                // -------------------- --------------------
                // Triangle                                3
                //
                ds_5_0
                dcl_input_control_point_count 3
                dcl_tessellator_domain domain_tri
                dcl_globalFlags refactoringAllowed
                dcl_constantbuffer cb0[13], immediateIndexed
                dcl_input vDomain.xyz
                dcl_input vicp[3][0].xyzw
                dcl_input vicp[3][1].xyzw
                dcl_input vicp[3][2].xyz
                dcl_input vicp[3][3].xyz
                dcl_input vicp[3][4].xyz
                dcl_input vicp[3][5].xyz
                dcl_input vicp[3][6].xyz
                dcl_output o0.xyzw
                dcl_output o1.xyzw
                dcl_output o2.xyz
                dcl_output o3.xyz
                dcl_output o4.xyz
                dcl_output o5.xyz
                dcl_output_siv o6.xyzw, position
                dcl_temps 2
                mul r0.xyzw, vDomain.yyyy, vicp[1][0].xyzw
                mad r0.xyzw, vDomain.xxxx, vicp[0][0].xyzw, r0.xyzw
                mad o0.xyzw, vDomain.zzzz, vicp[2][0].xyzw, r0.xyzw
                mul r0.xyzw, vDomain.yyyy, vicp[1][1].xyzw
                mad r0.xyzw, vDomain.xxxx, vicp[0][1].xyzw, r0.xyzw
                mad o1.xyzw, vDomain.zzzz, vicp[2][1].xyzw, r0.xyzw
                mul r0.xyz, vDomain.yyyy, vicp[1][2].xyzx
                mad r0.xyz, vDomain.xxxx, vicp[0][2].xyzx, r0.xyzx
                mad o2.xyz, vDomain.zzzz, vicp[2][2].xyzx, r0.xyzx
                mul r0.xyz, vDomain.yyyy, vicp[1][3].xyzx
                mad r0.xyz, vDomain.xxxx, vicp[0][3].xyzx, r0.xyzx
                mad o3.xyz, vDomain.zzzz, vicp[2][3].xyzx, r0.xyzx
                mul r0.xyz, vDomain.yyyy, vicp[1][4].xyzx
                mad r0.xyz, vDomain.xxxx, vicp[0][4].xyzx, r0.xyzx
                mad o4.xyz, vDomain.zzzz, vicp[2][4].xyzx, r0.xyzx
                mul r0.xyz, vDomain.yyyy, vicp[1][5].xyzx
                mad r0.xyz, vDomain.xxxx, vicp[0][5].xyzx, r0.xyzx
                mad o5.xyz, vDomain.zzzz, vicp[2][5].xyzx, r0.xyzx
                mul r0.xyz, vDomain.yyyy, vicp[1][6].xyzx
                mad r0.xyz, vDomain.xxxx, vicp[0][6].xyzx, r0.xyzx
                mad r0.xyz, vDomain.zzzz, vicp[2][6].xyzx, r0.xyzx
                mul r1.xyzw, r0.yyyy, cb0[10].xyzw
                mad r1.xyzw, cb0[9].xyzw, r0.xxxx, r1.xyzw
                mad r0.xyzw, cb0[11].xyzw, r0.zzzz, r1.xyzw
                add o6.xyzw, r0.xyzw, cb0[12].xyzw
                ret 
                // Approximately 26 instruction slots used
                            
            };
            PixelShader = asm {
                //
                // Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.16384
                //
                //
                //
                // Input signature:
                //
                // Name                 Index   Mask Register SysValue  Format   Used
                // -------------------- ----- ------ -------- -------- ------- ------
                // no Input
                //
                // Output signature:
                //
                // Name                 Index   Mask Register SysValue  Format   Used
                // -------------------- ----- ------ -------- -------- ------- ------
                // SV_TARGET                0   xyzw        0   TARGET   float   xyzw
                //
                ps_5_0
                dcl_globalFlags refactoringAllowed
                dcl_output o0.xyzw
                mov o0.xyzw, l(1.000000,1.000000,1.000000,1.000000)
                ret 
                // Approximately 2 instruction slots used
                            
            };
        }

    }

}

#endif

const BYTE g_Shadertesttess[] =
{
      1,  32, 255, 254,   1,   0, 
      0,   0,   7,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   1,   0, 
      0,   0, 221,  36,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   6,   0,   0,   0, 
      6,   0,   0,   0,   1,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,  36,  71, 
    108, 111,  98,  97, 108, 115, 
      0, 102, 108, 111,  97, 116, 
     52,   0,  13,   0,   0,   0, 
      1,   0,   0,   0,   0,   0, 
      0,   0,  16,   0,   0,   0, 
     16,   0,   0,   0,  16,   0, 
      0,   0,  10,  33,   0,   0, 
    103,  95, 118,  84, 101, 115, 
    115, 101, 108, 108,  97, 116, 
    105, 111, 110,  70,  97,  99, 
    116, 111, 114,   0, 102, 108, 
    111,  97, 116,  52, 120,  52, 
      0,  70,   0,   0,   0,   1, 
      0,   0,   0,   0,   0,   0, 
      0,  64,   0,   0,   0,  64, 
      0,   0,   0,  64,   0,   0, 
      0,  11, 100,   0,   0, 103, 
     95, 119, 111, 114, 108, 100, 
      0,  87, 111, 114, 108, 100, 
      0, 103,  95, 118, 112,   0, 
     86, 105, 101, 119,  80, 114, 
    111, 106, 101,  99, 116, 105, 
    111, 110,   0, 103,  95, 119, 
    118, 112,   0,  87, 111, 114, 
    108, 100,  86, 105, 101, 119, 
     80, 114, 111, 106, 101,  99, 
    116, 105, 111, 110,   0, 103, 
     95, 117, 118,  84, 114,  97, 
    110, 115, 102, 111, 114, 109, 
      0,   0,   0, 128,  63,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0, 128, 
     63,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0, 128,  63,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0, 128,  63, 102, 
    108, 111,  97, 116,   0, 245, 
      0,   0,   0,   1,   0,   0, 
      0,   0,   0,   0,   0,   4, 
      0,   0,   0,  16,   0,   0, 
      0,   4,   0,   0,   0,   9, 
      9,   0,   0, 103,  95, 103, 
    108, 111, 119,  83, 105, 122, 
    101,   0,   0,   0,   0,   0, 
    103,  95,  98, 117, 109, 112, 
     77,  97, 112,  83,  99,  97, 
    108, 101,   0,  66, 117, 109, 
    112,  77,  97, 112,  83,  99, 
     97, 108, 101,   0,   0,   0, 
    128,  63,  68, 101, 102,  97, 
    117, 108, 116,   0,  80,  68, 
    101, 102,  97, 117, 108, 116, 
      0, 200,   5,   0,   0,  68, 
     88,  66,  67,  89, 199, 193, 
    253, 188,  67, 187,   4,  34, 
    174, 224, 227, 252, 100,  80, 
    212,   1,   0,   0,   0, 200, 
      5,   0,   0,   5,   0,   0, 
      0,  52,   0,   0,   0,  48, 
      3,   0,   0, 232,   3,   0, 
      0,  28,   4,   0,   0,  44, 
      5,   0,   0,  82,  68,  69, 
     70, 244,   2,   0,   0,   1, 
      0,   0,   0, 104,   0,   0, 
      0,   1,   0,   0,   0,  60, 
      0,   0,   0,   0,   5, 254, 
    255,   0,   1,   0,   0, 192, 
      2,   0,   0,  82,  68,  49, 
     49,  60,   0,   0,   0,  24, 
      0,   0,   0,  32,   0,   0, 
      0,  40,   0,   0,   0,  36, 
      0,   0,   0,  12,   0,   0, 
      0,   0,   0,   0,   0,  92, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   1, 
      0,   0,   0,   0,   0,   0, 
      0,  36,  71, 108, 111,  98, 
     97, 108, 115,   0, 171, 171, 
    171,  92,   0,   0,   0,   7, 
      0,   0,   0, 128,   0,   0, 
      0,  32,   1,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0, 152,   1,   0,   0,   0, 
      0,   0,   0,  16,   0,   0, 
      0,   0,   0,   0,   0, 184, 
      1,   0,   0,   0,   0,   0, 
      0, 255, 255, 255, 255,   0, 
      0,   0,   0, 255, 255, 255, 
    255,   0,   0,   0,   0, 220, 
      1,   0,   0,  16,   0,   0, 
      0,  64,   0,   0,   0,   0, 
      0,   0,   0, 240,   1,   0, 
      0,   0,   0,   0,   0, 255, 
    255, 255, 255,   0,   0,   0, 
      0, 255, 255, 255, 255,   0, 
      0,   0,   0,  20,   2,   0, 
      0,  80,   0,   0,   0,  64, 
      0,   0,   0,   0,   0,   0, 
      0, 240,   1,   0,   0,   0, 
      0,   0,   0, 255, 255, 255, 
    255,   0,   0,   0,   0, 255, 
    255, 255, 255,   0,   0,   0, 
      0,  25,   2,   0,   0, 144, 
      0,   0,   0,  64,   0,   0, 
      0,   2,   0,   0,   0, 240, 
      1,   0,   0,   0,   0,   0, 
      0, 255, 255, 255, 255,   0, 
      0,   0,   0, 255, 255, 255, 
    255,   0,   0,   0,   0,  31, 
      2,   0,   0, 208,   0,   0, 
      0,  64,   0,   0,   0,   0, 
      0,   0,   0, 240,   1,   0, 
      0,  48,   2,   0,   0, 255, 
    255, 255, 255,   0,   0,   0, 
      0, 255, 255, 255, 255,   0, 
      0,   0,   0, 112,   2,   0, 
      0,  16,   1,   0,   0,   4, 
      0,   0,   0,   2,   0,   0, 
      0, 132,   2,   0,   0, 168, 
      2,   0,   0, 255, 255, 255, 
    255,   0,   0,   0,   0, 255, 
    255, 255, 255,   0,   0,   0, 
      0, 172,   2,   0,   0,  20, 
      1,   0,   0,   4,   0,   0, 
      0,   0,   0,   0,   0, 132, 
      2,   0,   0, 188,   2,   0, 
      0, 255, 255, 255, 255,   0, 
      0,   0,   0, 255, 255, 255, 
    255,   0,   0,   0,   0, 103, 
     95, 118,  84, 101, 115, 115, 
    101, 108, 108,  97, 116, 105, 
    111, 110,  70,  97,  99, 116, 
    111, 114,   0, 102, 108, 111, 
     97, 116,  52,   0, 171, 171, 
    171,   1,   0,   3,   0,   1, 
      0,   4,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0, 174,   1,   0, 
      0, 103,  95, 119, 111, 114, 
    108, 100,   0, 102, 108, 111, 
     97, 116,  52, 120,  52,   0, 
    171, 171, 171,   3,   0,   3, 
      0,   4,   0,   4,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0, 228, 
      1,   0,   0, 103,  95, 118, 
    112,   0, 103,  95, 119, 118, 
    112,   0, 103,  95, 117, 118, 
     84, 114,  97, 110, 115, 102, 
    111, 114, 109,   0, 171, 171, 
    171,   0,   0, 128,  63,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0, 128, 
     63,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0, 128,  63,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0, 128,  63, 103, 
     95, 103, 108, 111, 119,  83, 
    105, 122, 101,   0, 102, 108, 
    111,  97, 116,   0, 171, 171, 
    171,   0,   0,   3,   0,   1, 
      0,   1,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0, 123,   2,   0, 
      0,   0,   0,   0,   0, 103, 
     95,  98, 117, 109, 112,  77, 
     97, 112,  83,  99,  97, 108, 
    101,   0, 171,   0,   0, 128, 
     63,  77, 105,  99, 114, 111, 
    115, 111, 102, 116,  32,  40, 
     82,  41,  32,  72,  76,  83, 
     76,  32,  83, 104,  97, 100, 
    101, 114,  32,  67, 111, 109, 
    112, 105, 108, 101, 114,  32, 
     57,  46,  51,  48,  46,  57, 
     50,  48,  48,  46,  49,  54, 
     51,  56,  52,   0, 171,  73, 
     83,  71,  78, 176,   0,   0, 
      0,   5,   0,   0,   0,   8, 
      0,   0,   0, 128,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   3,   0,   0, 
      0,   0,   0,   0,   0,   7, 
      7,   0,   0, 140,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   3,   0,   0, 
      0,   1,   0,   0,   0,   7, 
      7,   0,   0, 147,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   3,   0,   0, 
      0,   2,   0,   0,   0,   3, 
      0,   0,   0, 156,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   3,   0,   0, 
      0,   3,   0,   0,   0,   7, 
      0,   0,   0, 164,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   3,   0,   0, 
      0,   4,   0,   0,   0,   7, 
      0,   0,   0,  83,  86,  95, 
     80,  79,  83,  73,  84,  73, 
     79,  78,   0,  78,  79,  82, 
     77,  65,  76,   0,  84,  69, 
     88,  67,  79,  79,  82,  68, 
      0,  84,  65,  78,  71,  69, 
     78,  84,   0,  66,  73,  78, 
     79,  82,  77,  65,  76,   0, 
    171, 171, 171,  79,  83,  71, 
     78,  44,   0,   0,   0,   1, 
      0,   0,   0,   8,   0,   0, 
      0,  32,   0,   0,   0,   0, 
      0,   0,   0,   1,   0,   0, 
      0,   3,   0,   0,   0,   0, 
      0,   0,   0,  15,   0,   0, 
      0,  83,  86,  95,  80,  79, 
     83,  73,  84,  73,  79,  78, 
      0,  83,  72,  69,  88,   8, 
      1,   0,   0,  80,   0,   1, 
      0,  66,   0,   0,   0, 106, 
      8,   0,   1,  89,   0,   0, 
      4,  70, 142,  32,   0,   0, 
      0,   0,   0,  18,   0,   0, 
      0,  95,   0,   0,   3, 114, 
     16,  16,   0,   0,   0,   0, 
      0,  95,   0,   0,   3, 114, 
     16,  16,   0,   1,   0,   0, 
      0, 103,   0,   0,   4, 242, 
     32,  16,   0,   0,   0,   0, 
      0,   1,   0,   0,   0, 104, 
      0,   0,   2,   2,   0,   0, 
      0,  50,   0,   0,  10, 114, 
      0,  16,   0,   0,   0,   0, 
      0,  70,  18,  16,   0,   1, 
      0,   0,   0,   6, 128,  32, 
      0,   0,   0,   0,   0,  17, 
      0,   0,   0,  70,  18,  16, 
      0,   0,   0,   0,   0,  56, 
      0,   0,   8, 242,   0,  16, 
      0,   1,   0,   0,   0,  86, 
      5,  16,   0,   0,   0,   0, 
      0,  70, 142,  32,   0,   0, 
      0,   0,   0,  10,   0,   0, 
      0,  50,   0,   0,  10, 242, 
      0,  16,   0,   1,   0,   0, 
      0,  70, 142,  32,   0,   0, 
      0,   0,   0,   9,   0,   0, 
      0,   6,   0,  16,   0,   0, 
      0,   0,   0,  70,  14,  16, 
      0,   1,   0,   0,   0,  50, 
      0,   0,  10, 242,   0,  16, 
      0,   0,   0,   0,   0,  70, 
    142,  32,   0,   0,   0,   0, 
      0,  11,   0,   0,   0, 166, 
     10,  16,   0,   0,   0,   0, 
      0,  70,  14,  16,   0,   1, 
      0,   0,   0,   0,   0,   0, 
      8, 242,  32,  16,   0,   0, 
      0,   0,   0,  70,  14,  16, 
      0,   0,   0,   0,   0,  70, 
    142,  32,   0,   0,   0,   0, 
      0,  12,   0,   0,   0,  62, 
      0,   0,   1,  83,  84,  65, 
     84, 148,   0,   0,   0,   6, 
      0,   0,   0,   2,   0,   0, 
      0,   0,   0,   0,   0,   3, 
      0,   0,   0,   2,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   1,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   1,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,  87,   1,   0, 
      0,   0,   0,   0,   0, 208, 
      1,   0,   0,  68,  88,  66, 
     67, 249,  23, 206,  58, 142, 
    253,  97, 177, 121, 104, 240, 
     70,  57,  87, 218,  93,   1, 
      0,   0,   0, 208,   1,   0, 
      0,   5,   0,   0,   0,  52, 
      0,   0,   0, 172,   0,   0, 
      0, 188,   0,   0,   0, 240, 
      0,   0,   0,  52,   1,   0, 
      0,  82,  68,  69,  70, 112, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,  60,   0,   0, 
      0,   0,   5, 255, 255,   0, 
      1,   0,   0,  60,   0,   0, 
      0,  82,  68,  49,  49,  60, 
      0,   0,   0,  24,   0,   0, 
      0,  32,   0,   0,   0,  40, 
      0,   0,   0,  36,   0,   0, 
      0,  12,   0,   0,   0,   0, 
      0,   0,   0,  77, 105,  99, 
    114, 111, 115, 111, 102, 116, 
     32,  40,  82,  41,  32,  72, 
     76,  83,  76,  32,  83, 104, 
     97, 100, 101, 114,  32,  67, 
    111, 109, 112, 105, 108, 101, 
    114,  32,  57,  46,  51,  48, 
     46,  57,  50,  48,  48,  46, 
     49,  54,  51,  56,  52,   0, 
    171,  73,  83,  71,  78,   8, 
      0,   0,   0,   0,   0,   0, 
      0,   8,   0,   0,   0,  79, 
     83,  71,  78,  44,   0,   0, 
      0,   1,   0,   0,   0,   8, 
      0,   0,   0,  32,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   3,   0,   0, 
      0,   0,   0,   0,   0,  15, 
      0,   0,   0,  83,  86,  95, 
     84,  65,  82,  71,  69,  84, 
      0, 171, 171,  83,  72,  69, 
     88,  60,   0,   0,   0,  80, 
      0,   0,   0,  15,   0,   0, 
      0, 106,   8,   0,   1, 101, 
      0,   0,   3, 242,  32,  16, 
      0,   0,   0,   0,   0,  54, 
      0,   0,   8, 242,  32,  16, 
      0,   0,   0,   0,   0,   2, 
     64,   0,   0,   0,   0, 128, 
     63,   0,   0, 128,  63,   0, 
      0, 128,  63,   0,   0, 128, 
     63,  62,   0,   0,   1,  83, 
     84,  65,  84, 148,   0,   0, 
      0,   2,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   1,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   1, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   2, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,  43, 
      7,   0,   0,   0,   0,   0, 
      0,  80,  84, 101, 115, 115, 
      0, 160,   8,   0,   0,  68, 
     88,  66,  67,  48, 179, 114, 
    196, 143, 215, 114,  67,  86, 
    106,  75, 204, 207, 148,   0, 
    160,   1,   0,   0,   0, 160, 
      8,   0,   0,   5,   0,   0, 
      0,  52,   0,   0,   0,  48, 
      3,   0,   0, 232,   3,   0, 
      0, 172,   4,   0,   0,   4, 
      8,   0,   0,  82,  68,  69, 
     70, 244,   2,   0,   0,   1, 
      0,   0,   0, 104,   0,   0, 
      0,   1,   0,   0,   0,  60, 
      0,   0,   0,   0,   5, 254, 
    255,   0,   1,   0,   0, 192, 
      2,   0,   0,  82,  68,  49, 
     49,  60,   0,   0,   0,  24, 
      0,   0,   0,  32,   0,   0, 
      0,  40,   0,   0,   0,  36, 
      0,   0,   0,  12,   0,   0, 
      0,   0,   0,   0,   0,  92, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   1, 
      0,   0,   0,   0,   0,   0, 
      0,  36,  71, 108, 111,  98, 
     97, 108, 115,   0, 171, 171, 
    171,  92,   0,   0,   0,   7, 
      0,   0,   0, 128,   0,   0, 
      0,  32,   1,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0, 152,   1,   0,   0,   0, 
      0,   0,   0,  16,   0,   0, 
      0,   0,   0,   0,   0, 184, 
      1,   0,   0,   0,   0,   0, 
      0, 255, 255, 255, 255,   0, 
      0,   0,   0, 255, 255, 255, 
    255,   0,   0,   0,   0, 220, 
      1,   0,   0,  16,   0,   0, 
      0,  64,   0,   0,   0,   2, 
      0,   0,   0, 240,   1,   0, 
      0,   0,   0,   0,   0, 255, 
    255, 255, 255,   0,   0,   0, 
      0, 255, 255, 255, 255,   0, 
      0,   0,   0,  20,   2,   0, 
      0,  80,   0,   0,   0,  64, 
      0,   0,   0,   0,   0,   0, 
      0, 240,   1,   0,   0,   0, 
      0,   0,   0, 255, 255, 255, 
    255,   0,   0,   0,   0, 255, 
    255, 255, 255,   0,   0,   0, 
      0,  25,   2,   0,   0, 144, 
      0,   0,   0,  64,   0,   0, 
      0,   0,   0,   0,   0, 240, 
      1,   0,   0,   0,   0,   0, 
      0, 255, 255, 255, 255,   0, 
      0,   0,   0, 255, 255, 255, 
    255,   0,   0,   0,   0,  31, 
      2,   0,   0, 208,   0,   0, 
      0,  64,   0,   0,   0,   2, 
      0,   0,   0, 240,   1,   0, 
      0,  48,   2,   0,   0, 255, 
    255, 255, 255,   0,   0,   0, 
      0, 255, 255, 255, 255,   0, 
      0,   0,   0, 112,   2,   0, 
      0,  16,   1,   0,   0,   4, 
      0,   0,   0,   2,   0,   0, 
      0, 132,   2,   0,   0, 168, 
      2,   0,   0, 255, 255, 255, 
    255,   0,   0,   0,   0, 255, 
    255, 255, 255,   0,   0,   0, 
      0, 172,   2,   0,   0,  20, 
      1,   0,   0,   4,   0,   0, 
      0,   0,   0,   0,   0, 132, 
      2,   0,   0, 188,   2,   0, 
      0, 255, 255, 255, 255,   0, 
      0,   0,   0, 255, 255, 255, 
    255,   0,   0,   0,   0, 103, 
     95, 118,  84, 101, 115, 115, 
    101, 108, 108,  97, 116, 105, 
    111, 110,  70,  97,  99, 116, 
    111, 114,   0, 102, 108, 111, 
     97, 116,  52,   0, 171, 171, 
    171,   1,   0,   3,   0,   1, 
      0,   4,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0, 174,   1,   0, 
      0, 103,  95, 119, 111, 114, 
    108, 100,   0, 102, 108, 111, 
     97, 116,  52, 120,  52,   0, 
    171, 171, 171,   3,   0,   3, 
      0,   4,   0,   4,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0, 228, 
      1,   0,   0, 103,  95, 118, 
    112,   0, 103,  95, 119, 118, 
    112,   0, 103,  95, 117, 118, 
     84, 114,  97, 110, 115, 102, 
    111, 114, 109,   0, 171, 171, 
    171,   0,   0, 128,  63,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0, 128, 
     63,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0, 128,  63,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0, 128,  63, 103, 
     95, 103, 108, 111, 119,  83, 
    105, 122, 101,   0, 102, 108, 
    111,  97, 116,   0, 171, 171, 
    171,   0,   0,   3,   0,   1, 
      0,   1,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0, 123,   2,   0, 
      0,   0,   0,   0,   0, 103, 
     95,  98, 117, 109, 112,  77, 
     97, 112,  83,  99,  97, 108, 
    101,   0, 171,   0,   0, 128, 
     63,  77, 105,  99, 114, 111, 
    115, 111, 102, 116,  32,  40, 
     82,  41,  32,  72,  76,  83, 
     76,  32,  83, 104,  97, 100, 
    101, 114,  32,  67, 111, 109, 
    112, 105, 108, 101, 114,  32, 
     57,  46,  51,  48,  46,  57, 
     50,  48,  48,  46,  49,  54, 
     51,  56,  52,   0, 171,  73, 
     83,  71,  78, 176,   0,   0, 
      0,   5,   0,   0,   0,   8, 
      0,   0,   0, 128,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   3,   0,   0, 
      0,   0,   0,   0,   0,   7, 
      7,   0,   0, 140,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   3,   0,   0, 
      0,   1,   0,   0,   0,   7, 
      7,   0,   0, 147,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   3,   0,   0, 
      0,   2,   0,   0,   0,   3, 
      3,   0,   0, 156,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   3,   0,   0, 
      0,   3,   0,   0,   0,   7, 
      7,   0,   0, 164,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   3,   0,   0, 
      0,   4,   0,   0,   0,   7, 
      7,   0,   0,  83,  86,  95, 
     80,  79,  83,  73,  84,  73, 
     79,  78,   0,  78,  79,  82, 
     77,  65,  76,   0,  84,  69, 
     88,  67,  79,  79,  82,  68, 
      0,  84,  65,  78,  71,  69, 
     78,  84,   0,  66,  73,  78, 
     79,  82,  77,  65,  76,   0, 
    171, 171, 171,  79,  83,  71, 
     78, 188,   0,   0,   0,   7, 
      0,   0,   0,   8,   0,   0, 
      0, 176,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   3,   0,   0,   0,   0, 
      0,   0,   0,  15,   0,   0, 
      0, 176,   0,   0,   0,   1, 
      0,   0,   0,   0,   0,   0, 
      0,   3,   0,   0,   0,   1, 
      0,   0,   0,  15,   0,   0, 
      0, 176,   0,   0,   0,   2, 
      0,   0,   0,   0,   0,   0, 
      0,   3,   0,   0,   0,   2, 
      0,   0,   0,   7,   8,   0, 
      0, 176,   0,   0,   0,   3, 
      0,   0,   0,   0,   0,   0, 
      0,   3,   0,   0,   0,   3, 
      0,   0,   0,   7,   8,   0, 
      0, 176,   0,   0,   0,   4, 
      0,   0,   0,   0,   0,   0, 
      0,   3,   0,   0,   0,   4, 
      0,   0,   0,   7,   8,   0, 
      0, 176,   0,   0,   0,   5, 
      0,   0,   0,   0,   0,   0, 
      0,   3,   0,   0,   0,   5, 
      0,   0,   0,   7,   8,   0, 
      0, 176,   0,   0,   0,   6, 
      0,   0,   0,   0,   0,   0, 
      0,   3,   0,   0,   0,   6, 
      0,   0,   0,   7,   8,   0, 
      0,  84,  69,  88,  67,  79, 
     79,  82,  68,   0, 171, 171, 
    171,  83,  72,  69,  88,  80, 
      3,   0,   0,  80,   0,   1, 
      0, 212,   0,   0,   0, 106, 
      8,   0,   1,  89,   0,   0, 
      4,  70, 142,  32,   0,   0, 
      0,   0,   0,  18,   0,   0, 
      0,  95,   0,   0,   3, 114, 
     16,  16,   0,   0,   0,   0, 
      0,  95,   0,   0,   3, 114, 
     16,  16,   0,   1,   0,   0, 
      0,  95,   0,   0,   3,  50, 
     16,  16,   0,   2,   0,   0, 
      0,  95,   0,   0,   3, 114, 
     16,  16,   0,   3,   0,   0, 
      0,  95,   0,   0,   3, 114, 
     16,  16,   0,   4,   0,   0, 
      0, 101,   0,   0,   3, 242, 
     32,  16,   0,   0,   0,   0, 
      0, 101,   0,   0,   3, 242, 
     32,  16,   0,   1,   0,   0, 
      0, 101,   0,   0,   3, 114, 
     32,  16,   0,   2,   0,   0, 
      0, 101,   0,   0,   3, 114, 
     32,  16,   0,   3,   0,   0, 
      0, 101,   0,   0,   3, 114, 
     32,  16,   0,   4,   0,   0, 
      0, 101,   0,   0,   3, 114, 
     32,  16,   0,   5,   0,   0, 
      0, 101,   0,   0,   3, 114, 
     32,  16,   0,   6,   0,   0, 
      0, 104,   0,   0,   2,   2, 
      0,   0,   0,  56,   0,   0, 
      8, 242,   0,  16,   0,   0, 
      0,   0,   0,  86,  21,  16, 
      0,   2,   0,   0,   0,  70, 
    142,  32,   0,   0,   0,   0, 
      0,  14,   0,   0,   0,  50, 
      0,   0,  10, 242,  32,  16, 
      0,   0,   0,   0,   0,  70, 
    142,  32,   0,   0,   0,   0, 
      0,  13,   0,   0,   0,   6, 
     16,  16,   0,   2,   0,   0, 
      0,  70,  14,  16,   0,   0, 
      0,   0,   0,  54,   0,   0, 
      5,  50,  32,  16,   0,   1, 
      0,   0,   0,  70,  16,  16, 
      0,   2,   0,   0,   0,  54, 
      0,   0,   8, 194,  32,  16, 
      0,   1,   0,   0,   0,   2, 
     64,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,  50,   0,   0,  10, 114, 
      0,  16,   0,   0,   0,   0, 
      0,  70,  18,  16,   0,   1, 
      0,   0,   0,   6, 128,  32, 
      0,   0,   0,   0,   0,  17, 
      0,   0,   0,  70,  18,  16, 
      0,   0,   0,   0,   0,  56, 
      0,   0,   8, 114,   0,  16, 
      0,   1,   0,   0,   0,  86, 
      5,  16,   0,   0,   0,   0, 
      0,  70, 130,  32,   0,   0, 
      0,   0,   0,   2,   0,   0, 
      0,  50,   0,   0,  10, 178, 
      0,  16,   0,   0,   0,   0, 
      0,  70, 136,  32,   0,   0, 
      0,   0,   0,   1,   0,   0, 
      0,   6,   0,  16,   0,   0, 
      0,   0,   0,  70,   8,  16, 
      0,   1,   0,   0,   0,  50, 
      0,   0,  10, 114,   0,  16, 
      0,   0,   0,   0,   0,  70, 
    130,  32,   0,   0,   0,   0, 
      0,   3,   0,   0,   0, 166, 
     10,  16,   0,   0,   0,   0, 
      0,  70,   3,  16,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      8, 114,  32,  16,   0,   2, 
      0,   0,   0,  70,   2,  16, 
      0,   0,   0,   0,   0,  70, 
    130,  32,   0,   0,   0,   0, 
      0,   4,   0,   0,   0,  56, 
      0,   0,   8, 114,   0,  16, 
      0,   0,   0,   0,   0,  86, 
     21,  16,   0,   3,   0,   0, 
      0,  70, 130,  32,   0,   0, 
      0,   0,   0,   2,   0,   0, 
      0,  50,   0,   0,  10, 114, 
      0,  16,   0,   0,   0,   0, 
      0,  70, 130,  32,   0,   0, 
      0,   0,   0,   1,   0,   0, 
      0,   6,  16,  16,   0,   3, 
      0,   0,   0,  70,   2,  16, 
      0,   0,   0,   0,   0,  50, 
      0,   0,  10, 114,  32,  16, 
      0,   3,   0,   0,   0,  70, 
    130,  32,   0,   0,   0,   0, 
      0,   3,   0,   0,   0, 166, 
     26,  16,   0,   3,   0,   0, 
      0,  70,   2,  16,   0,   0, 
      0,   0,   0,  56,   0,   0, 
      8, 114,   0,  16,   0,   0, 
      0,   0,   0,  86,  21,  16, 
      0,   4,   0,   0,   0,  70, 
    130,  32,   0,   0,   0,   0, 
      0,   2,   0,   0,   0,  50, 
      0,   0,  10, 114,   0,  16, 
      0,   0,   0,   0,   0,  70, 
    130,  32,   0,   0,   0,   0, 
      0,   1,   0,   0,   0,   6, 
     16,  16,   0,   4,   0,   0, 
      0,  70,   2,  16,   0,   0, 
      0,   0,   0,  50,   0,   0, 
     10, 114,  32,  16,   0,   4, 
      0,   0,   0,  70, 130,  32, 
      0,   0,   0,   0,   0,   3, 
      0,   0,   0, 166,  26,  16, 
      0,   4,   0,   0,   0,  70, 
      2,  16,   0,   0,   0,   0, 
      0,  56,   0,   0,   8, 114, 
      0,  16,   0,   0,   0,   0, 
      0,  86,  21,  16,   0,   1, 
      0,   0,   0,  70, 130,  32, 
      0,   0,   0,   0,   0,   2, 
      0,   0,   0,  50,   0,   0, 
     10, 114,   0,  16,   0,   0, 
      0,   0,   0,  70, 130,  32, 
      0,   0,   0,   0,   0,   1, 
      0,   0,   0,   6,  16,  16, 
      0,   1,   0,   0,   0,  70, 
      2,  16,   0,   0,   0,   0, 
      0,  50,   0,   0,  10, 114, 
     32,  16,   0,   5,   0,   0, 
      0,  70, 130,  32,   0,   0, 
      0,   0,   0,   3,   0,   0, 
      0, 166,  26,  16,   0,   1, 
      0,   0,   0,  70,   2,  16, 
      0,   0,   0,   0,   0,  54, 
      0,   0,   5, 114,  32,  16, 
      0,   6,   0,   0,   0,  70, 
     18,  16,   0,   0,   0,   0, 
      0,  62,   0,   0,   1,  83, 
     84,  65,  84, 148,   0,   0, 
      0,  20,   0,   0,   0,   2, 
      0,   0,   0,   0,   0,   0, 
      0,  12,   0,   0,   0,   6, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   1, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   4, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,  13, 
      9,   0,   0,   0,   0,   0, 
      0, 228,   6,   0,   0,  68, 
     88,  66,  67, 254, 243, 248, 
    121, 128,  82,   5,  53, 140, 
    223,  90, 120, 242, 146, 117, 
    213,   1,   0,   0,   0, 228, 
      6,   0,   0,   6,   0,   0, 
      0,  56,   0,   0,   0,  52, 
      3,   0,   0, 248,   3,   0, 
      0, 188,   4,   0,   0,  80, 
      5,   0,   0,  72,   6,   0, 
      0,  82,  68,  69,  70, 244, 
      2,   0,   0,   1,   0,   0, 
      0, 104,   0,   0,   0,   1, 
      0,   0,   0,  60,   0,   0, 
      0,   0,   5,  83,  72,   0, 
      1,   0,   0, 192,   2,   0, 
      0,  82,  68,  49,  49,  60, 
      0,   0,   0,  24,   0,   0, 
      0,  32,   0,   0,   0,  40, 
      0,   0,   0,  36,   0,   0, 
      0,  12,   0,   0,   0,   0, 
      0,   0,   0,  92,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   1,   0,   0, 
      0,   0,   0,   0,   0,  36, 
     71, 108, 111,  98,  97, 108, 
    115,   0, 171, 171, 171,  92, 
      0,   0,   0,   7,   0,   0, 
      0, 128,   0,   0,   0,  32, 
      1,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0, 152, 
      1,   0,   0,   0,   0,   0, 
      0,  16,   0,   0,   0,   2, 
      0,   0,   0, 184,   1,   0, 
      0,   0,   0,   0,   0, 255, 
    255, 255, 255,   0,   0,   0, 
      0, 255, 255, 255, 255,   0, 
      0,   0,   0, 220,   1,   0, 
      0,  16,   0,   0,   0,  64, 
      0,   0,   0,   0,   0,   0, 
      0, 240,   1,   0,   0,   0, 
      0,   0,   0, 255, 255, 255, 
    255,   0,   0,   0,   0, 255, 
    255, 255, 255,   0,   0,   0, 
      0,  20,   2,   0,   0,  80, 
      0,   0,   0,  64,   0,   0, 
      0,   0,   0,   0,   0, 240, 
      1,   0,   0,   0,   0,   0, 
      0, 255, 255, 255, 255,   0, 
      0,   0,   0, 255, 255, 255, 
    255,   0,   0,   0,   0,  25, 
      2,   0,   0, 144,   0,   0, 
      0,  64,   0,   0,   0,   0, 
      0,   0,   0, 240,   1,   0, 
      0,   0,   0,   0,   0, 255, 
    255, 255, 255,   0,   0,   0, 
      0, 255, 255, 255, 255,   0, 
      0,   0,   0,  31,   2,   0, 
      0, 208,   0,   0,   0,  64, 
      0,   0,   0,   0,   0,   0, 
      0, 240,   1,   0,   0,  48, 
      2,   0,   0, 255, 255, 255, 
    255,   0,   0,   0,   0, 255, 
    255, 255, 255,   0,   0,   0, 
      0, 112,   2,   0,   0,  16, 
      1,   0,   0,   4,   0,   0, 
      0,   0,   0,   0,   0, 132, 
      2,   0,   0, 168,   2,   0, 
      0, 255, 255, 255, 255,   0, 
      0,   0,   0, 255, 255, 255, 
    255,   0,   0,   0,   0, 172, 
      2,   0,   0,  20,   1,   0, 
      0,   4,   0,   0,   0,   0, 
      0,   0,   0, 132,   2,   0, 
      0, 188,   2,   0,   0, 255, 
    255, 255, 255,   0,   0,   0, 
      0, 255, 255, 255, 255,   0, 
      0,   0,   0, 103,  95, 118, 
     84, 101, 115, 115, 101, 108, 
    108,  97, 116, 105, 111, 110, 
     70,  97,  99, 116, 111, 114, 
      0, 102, 108, 111,  97, 116, 
     52,   0, 171, 171, 171,   1, 
      0,   3,   0,   1,   0,   4, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0, 174,   1,   0,   0, 103, 
     95, 119, 111, 114, 108, 100, 
      0, 102, 108, 111,  97, 116, 
     52, 120,  52,   0, 171, 171, 
    171,   3,   0,   3,   0,   4, 
      0,   4,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0, 228,   1,   0, 
      0, 103,  95, 118, 112,   0, 
    103,  95, 119, 118, 112,   0, 
    103,  95, 117, 118,  84, 114, 
     97, 110, 115, 102, 111, 114, 
    109,   0, 171, 171, 171,   0, 
      0, 128,  63,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0, 128,  63,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0, 128, 
     63,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0, 128,  63, 103,  95, 103, 
    108, 111, 119,  83, 105, 122, 
    101,   0, 102, 108, 111,  97, 
    116,   0, 171, 171, 171,   0, 
      0,   3,   0,   1,   0,   1, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0, 123,   2,   0,   0,   0, 
      0,   0,   0, 103,  95,  98, 
    117, 109, 112,  77,  97, 112, 
     83,  99,  97, 108, 101,   0, 
    171,   0,   0, 128,  63,  77, 
    105,  99, 114, 111, 115, 111, 
    102, 116,  32,  40,  82,  41, 
     32,  72,  76,  83,  76,  32, 
     83, 104,  97, 100, 101, 114, 
     32,  67, 111, 109, 112, 105, 
    108, 101, 114,  32,  57,  46, 
     51,  48,  46,  57,  50,  48, 
     48,  46,  49,  54,  51,  56, 
     52,   0, 171,  73,  83,  71, 
     78, 188,   0,   0,   0,   7, 
      0,   0,   0,   8,   0,   0, 
      0, 176,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   3,   0,   0,   0,   0, 
      0,   0,   0,  15,  15,   0, 
      0, 176,   0,   0,   0,   1, 
      0,   0,   0,   0,   0,   0, 
      0,   3,   0,   0,   0,   1, 
      0,   0,   0,  15,  15,   0, 
      0, 176,   0,   0,   0,   2, 
      0,   0,   0,   0,   0,   0, 
      0,   3,   0,   0,   0,   2, 
      0,   0,   0,   7,   7,   0, 
      0, 176,   0,   0,   0,   3, 
      0,   0,   0,   0,   0,   0, 
      0,   3,   0,   0,   0,   3, 
      0,   0,   0,   7,   7,   0, 
      0, 176,   0,   0,   0,   4, 
      0,   0,   0,   0,   0,   0, 
      0,   3,   0,   0,   0,   4, 
      0,   0,   0,   7,   7,   0, 
      0, 176,   0,   0,   0,   5, 
      0,   0,   0,   0,   0,   0, 
      0,   3,   0,   0,   0,   5, 
      0,   0,   0,   7,   7,   0, 
      0, 176,   0,   0,   0,   6, 
      0,   0,   0,   0,   0,   0, 
      0,   3,   0,   0,   0,   6, 
      0,   0,   0,   7,   7,   0, 
      0,  84,  69,  88,  67,  79, 
     79,  82,  68,   0, 171, 171, 
    171,  79,  83,  71,  78, 188, 
      0,   0,   0,   7,   0,   0, 
      0,   8,   0,   0,   0, 176, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   3, 
      0,   0,   0,   0,   0,   0, 
      0,  15,   0,   0,   0, 176, 
      0,   0,   0,   1,   0,   0, 
      0,   0,   0,   0,   0,   3, 
      0,   0,   0,   1,   0,   0, 
      0,  15,   0,   0,   0, 176, 
      0,   0,   0,   2,   0,   0, 
      0,   0,   0,   0,   0,   3, 
      0,   0,   0,   2,   0,   0, 
      0,   7,   8,   0,   0, 176, 
      0,   0,   0,   3,   0,   0, 
      0,   0,   0,   0,   0,   3, 
      0,   0,   0,   3,   0,   0, 
      0,   7,   8,   0,   0, 176, 
      0,   0,   0,   4,   0,   0, 
      0,   0,   0,   0,   0,   3, 
      0,   0,   0,   4,   0,   0, 
      0,   7,   8,   0,   0, 176, 
      0,   0,   0,   5,   0,   0, 
      0,   0,   0,   0,   0,   3, 
      0,   0,   0,   5,   0,   0, 
      0,   7,   8,   0,   0, 176, 
      0,   0,   0,   6,   0,   0, 
      0,   0,   0,   0,   0,   3, 
      0,   0,   0,   6,   0,   0, 
      0,   7,   8,   0,   0,  84, 
     69,  88,  67,  79,  79,  82, 
     68,   0, 171, 171, 171,  80, 
     67,  83,  71, 140,   0,   0, 
      0,   4,   0,   0,   0,   8, 
      0,   0,   0, 104,   0,   0, 
      0,   0,   0,   0,   0,  13, 
      0,   0,   0,   3,   0,   0, 
      0,   0,   0,   0,   0,   1, 
     14,   0,   0, 104,   0,   0, 
      0,   1,   0,   0,   0,  13, 
      0,   0,   0,   3,   0,   0, 
      0,   1,   0,   0,   0,   1, 
     14,   0,   0, 104,   0,   0, 
      0,   2,   0,   0,   0,  13, 
      0,   0,   0,   3,   0,   0, 
      0,   2,   0,   0,   0,   1, 
     14,   0,   0, 118,   0,   0, 
      0,   0,   0,   0,   0,  14, 
      0,   0,   0,   3,   0,   0, 
      0,   3,   0,   0,   0,   1, 
     14,   0,   0,  83,  86,  95, 
     84, 101, 115, 115,  70,  97, 
     99, 116, 111, 114,   0,  83, 
     86,  95,  73, 110, 115, 105, 
    100, 101,  84, 101, 115, 115, 
     70,  97,  99, 116, 111, 114, 
      0, 171, 171,  83,  72,  69, 
     88, 240,   0,   0,   0,  80, 
      0,   3,   0,  60,   0,   0, 
      0, 113,   0,   0,   1, 147, 
     24,   0,   1, 148,  24,   0, 
      1, 149,  16,   0,   1, 150, 
     24,   0,   1, 151,  24,   0, 
      1, 106,   8,   0,   1,  89, 
      0,   0,   4,  70, 142,  32, 
      0,   0,   0,   0,   0,   1, 
      0,   0,   0, 115,   0,   0, 
      1, 153,   0,   0,   2,   3, 
      0,   0,   0,  95,   0,   0, 
      2,   0, 112,   1,   0, 103, 
      0,   0,   4,  18,  32,  16, 
      0,   0,   0,   0,   0,  17, 
      0,   0,   0, 103,   0,   0, 
      4,  18,  32,  16,   0,   1, 
      0,   0,   0,  18,   0,   0, 
      0, 103,   0,   0,   4,  18, 
     32,  16,   0,   2,   0,   0, 
      0,  19,   0,   0,   0, 104, 
      0,   0,   2,   1,   0,   0, 
      0,  91,   0,   0,   4,  18, 
     32,  16,   0,   0,   0,   0, 
      0,   3,   0,   0,   0,  54, 
      0,   0,   4,  18,   0,  16, 
      0,   0,   0,   0,   0,  10, 
    112,   1,   0,  54,   0,   0, 
      7,  18,  32, 144,   0,  10, 
      0,  16,   0,   0,   0,   0, 
      0,  10, 128,  32,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,  62,   0,   0,   1, 115, 
      0,   0,   1, 103,   0,   0, 
      4,  18,  32,  16,   0,   3, 
      0,   0,   0,  20,   0,   0, 
      0,  54,   0,   0,   6,  18, 
     32,  16,   0,   3,   0,   0, 
      0,  26, 128,  32,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,  62,   0,   0,   1,  83, 
     84,  65,  84, 148,   0,   0, 
      0,   5,   0,   0,   0,   1, 
      0,   0,   0,   0,   0,   0, 
      0,   4,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,  10,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   3,   0,   0,   0,   3, 
      0,   0,   0,   3,   0,   0, 
      0,   2,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0, 185, 
     17,   0,   0,   0,   0,   0, 
      0,  76,  10,   0,   0,  68, 
     88,  66,  67, 157,  80, 166, 
    101,  23, 145,   9, 203, 113, 
    177,  46, 224, 188, 125,  60, 
     15,   1,   0,   0,   0,  76, 
     10,   0,   0,   6,   0,   0, 
      0,  56,   0,   0,   0,  52, 
      3,   0,   0, 248,   3,   0, 
      0, 140,   4,   0,   0,  92, 
      5,   0,   0, 176,   9,   0, 
      0,  82,  68,  69,  70, 244, 
      2,   0,   0,   1,   0,   0, 
      0, 104,   0,   0,   0,   1, 
      0,   0,   0,  60,   0,   0, 
      0,   0,   5,  83,  68,   0, 
      1,   0,   0, 192,   2,   0, 
      0,  82,  68,  49,  49,  60, 
      0,   0,   0,  24,   0,   0, 
      0,  32,   0,   0,   0,  40, 
      0,   0,   0,  36,   0,   0, 
      0,  12,   0,   0,   0,   0, 
      0,   0,   0,  92,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   1,   0,   0, 
      0,   0,   0,   0,   0,  36, 
     71, 108, 111,  98,  97, 108, 
    115,   0, 171, 171, 171,  92, 
      0,   0,   0,   7,   0,   0, 
      0, 128,   0,   0,   0,  32, 
      1,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0, 152, 
      1,   0,   0,   0,   0,   0, 
      0,  16,   0,   0,   0,   0, 
      0,   0,   0, 184,   1,   0, 
      0,   0,   0,   0,   0, 255, 
    255, 255, 255,   0,   0,   0, 
      0, 255, 255, 255, 255,   0, 
      0,   0,   0, 220,   1,   0, 
      0,  16,   0,   0,   0,  64, 
      0,   0,   0,   0,   0,   0, 
      0, 240,   1,   0,   0,   0, 
      0,   0,   0, 255, 255, 255, 
    255,   0,   0,   0,   0, 255, 
    255, 255, 255,   0,   0,   0, 
      0,  20,   2,   0,   0,  80, 
      0,   0,   0,  64,   0,   0, 
      0,   0,   0,   0,   0, 240, 
      1,   0,   0,   0,   0,   0, 
      0, 255, 255, 255, 255,   0, 
      0,   0,   0, 255, 255, 255, 
    255,   0,   0,   0,   0,  25, 
      2,   0,   0, 144,   0,   0, 
      0,  64,   0,   0,   0,   2, 
      0,   0,   0, 240,   1,   0, 
      0,   0,   0,   0,   0, 255, 
    255, 255, 255,   0,   0,   0, 
      0, 255, 255, 255, 255,   0, 
      0,   0,   0,  31,   2,   0, 
      0, 208,   0,   0,   0,  64, 
      0,   0,   0,   0,   0,   0, 
      0, 240,   1,   0,   0,  48, 
      2,   0,   0, 255, 255, 255, 
    255,   0,   0,   0,   0, 255, 
    255, 255, 255,   0,   0,   0, 
      0, 112,   2,   0,   0,  16, 
      1,   0,   0,   4,   0,   0, 
      0,   0,   0,   0,   0, 132, 
      2,   0,   0, 168,   2,   0, 
      0, 255, 255, 255, 255,   0, 
      0,   0,   0, 255, 255, 255, 
    255,   0,   0,   0,   0, 172, 
      2,   0,   0,  20,   1,   0, 
      0,   4,   0,   0,   0,   0, 
      0,   0,   0, 132,   2,   0, 
      0, 188,   2,   0,   0, 255, 
    255, 255, 255,   0,   0,   0, 
      0, 255, 255, 255, 255,   0, 
      0,   0,   0, 103,  95, 118, 
     84, 101, 115, 115, 101, 108, 
    108,  97, 116, 105, 111, 110, 
     70,  97,  99, 116, 111, 114, 
      0, 102, 108, 111,  97, 116, 
     52,   0, 171, 171, 171,   1, 
      0,   3,   0,   1,   0,   4, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0, 174,   1,   0,   0, 103, 
     95, 119, 111, 114, 108, 100, 
      0, 102, 108, 111,  97, 116, 
     52, 120,  52,   0, 171, 171, 
    171,   3,   0,   3,   0,   4, 
      0,   4,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0, 228,   1,   0, 
      0, 103,  95, 118, 112,   0, 
    103,  95, 119, 118, 112,   0, 
    103,  95, 117, 118,  84, 114, 
     97, 110, 115, 102, 111, 114, 
    109,   0, 171, 171, 171,   0, 
      0, 128,  63,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0, 128,  63,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0, 128, 
     63,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0, 128,  63, 103,  95, 103, 
    108, 111, 119,  83, 105, 122, 
    101,   0, 102, 108, 111,  97, 
    116,   0, 171, 171, 171,   0, 
      0,   3,   0,   1,   0,   1, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0, 123,   2,   0,   0,   0, 
      0,   0,   0, 103,  95,  98, 
    117, 109, 112,  77,  97, 112, 
     83,  99,  97, 108, 101,   0, 
    171,   0,   0, 128,  63,  77, 
    105,  99, 114, 111, 115, 111, 
    102, 116,  32,  40,  82,  41, 
     32,  72,  76,  83,  76,  32, 
     83, 104,  97, 100, 101, 114, 
     32,  67, 111, 109, 112, 105, 
    108, 101, 114,  32,  57,  46, 
     51,  48,  46,  57,  50,  48, 
     48,  46,  49,  54,  51,  56, 
     52,   0, 171,  73,  83,  71, 
     78, 188,   0,   0,   0,   7, 
      0,   0,   0,   8,   0,   0, 
      0, 176,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   3,   0,   0,   0,   0, 
      0,   0,   0,  15,  15,   0, 
      0, 176,   0,   0,   0,   1, 
      0,   0,   0,   0,   0,   0, 
      0,   3,   0,   0,   0,   1, 
      0,   0,   0,  15,  15,   0, 
      0, 176,   0,   0,   0,   2, 
      0,   0,   0,   0,   0,   0, 
      0,   3,   0,   0,   0,   2, 
      0,   0,   0,   7,   7,   0, 
      0, 176,   0,   0,   0,   3, 
      0,   0,   0,   0,   0,   0, 
      0,   3,   0,   0,   0,   3, 
      0,   0,   0,   7,   7,   0, 
      0, 176,   0,   0,   0,   4, 
      0,   0,   0,   0,   0,   0, 
      0,   3,   0,   0,   0,   4, 
      0,   0,   0,   7,   7,   0, 
      0, 176,   0,   0,   0,   5, 
      0,   0,   0,   0,   0,   0, 
      0,   3,   0,   0,   0,   5, 
      0,   0,   0,   7,   7,   0, 
      0, 176,   0,   0,   0,   6, 
      0,   0,   0,   0,   0,   0, 
      0,   3,   0,   0,   0,   6, 
      0,   0,   0,   7,   7,   0, 
      0,  84,  69,  88,  67,  79, 
     79,  82,  68,   0, 171, 171, 
    171,  80,  67,  83,  71, 140, 
      0,   0,   0,   4,   0,   0, 
      0,   8,   0,   0,   0, 104, 
      0,   0,   0,   0,   0,   0, 
      0,  13,   0,   0,   0,   3, 
      0,   0,   0,   0,   0,   0, 
      0,   1,   0,   0,   0, 104, 
      0,   0,   0,   1,   0,   0, 
      0,  13,   0,   0,   0,   3, 
      0,   0,   0,   1,   0,   0, 
      0,   1,   0,   0,   0, 104, 
      0,   0,   0,   2,   0,   0, 
      0,  13,   0,   0,   0,   3, 
      0,   0,   0,   2,   0,   0, 
      0,   1,   0,   0,   0, 118, 
      0,   0,   0,   0,   0,   0, 
      0,  14,   0,   0,   0,   3, 
      0,   0,   0,   3,   0,   0, 
      0,   1,   0,   0,   0,  83, 
     86,  95,  84, 101, 115, 115, 
     70,  97,  99, 116, 111, 114, 
      0,  83,  86,  95,  73, 110, 
    115, 105, 100, 101,  84, 101, 
    115, 115,  70,  97,  99, 116, 
    111, 114,   0, 171, 171,  79, 
     83,  71,  78, 200,   0,   0, 
      0,   7,   0,   0,   0,   8, 
      0,   0,   0, 176,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   3,   0,   0, 
      0,   0,   0,   0,   0,  15, 
      0,   0,   0, 176,   0,   0, 
      0,   1,   0,   0,   0,   0, 
      0,   0,   0,   3,   0,   0, 
      0,   1,   0,   0,   0,  15, 
      0,   0,   0, 176,   0,   0, 
      0,   2,   0,   0,   0,   0, 
      0,   0,   0,   3,   0,   0, 
      0,   2,   0,   0,   0,   7, 
      8,   0,   0, 176,   0,   0, 
      0,   3,   0,   0,   0,   0, 
      0,   0,   0,   3,   0,   0, 
      0,   3,   0,   0,   0,   7, 
      8,   0,   0, 176,   0,   0, 
      0,   4,   0,   0,   0,   0, 
      0,   0,   0,   3,   0,   0, 
      0,   4,   0,   0,   0,   7, 
      8,   0,   0, 176,   0,   0, 
      0,   5,   0,   0,   0,   0, 
      0,   0,   0,   3,   0,   0, 
      0,   5,   0,   0,   0,   7, 
      8,   0,   0, 185,   0,   0, 
      0,   0,   0,   0,   0,   1, 
      0,   0,   0,   3,   0,   0, 
      0,   6,   0,   0,   0,  15, 
      0,   0,   0,  84,  69,  88, 
     67,  79,  79,  82,  68,   0, 
     83,  86,  95,  80,  79,  83, 
     73,  84,  73,  79,  78,   0, 
    171, 171, 171,  83,  72,  69, 
     88,  76,   4,   0,   0,  80, 
      0,   4,   0,  19,   1,   0, 
      0, 147,  24,   0,   1, 149, 
     16,   0,   1, 106,   8,   0, 
      1,  89,   0,   0,   4,  70, 
    142,  32,   0,   0,   0,   0, 
      0,  13,   0,   0,   0,  95, 
      0,   0,   2, 114, 192,   1, 
      0,  95,   0,   0,   4, 242, 
    144,  33,   0,   3,   0,   0, 
      0,   0,   0,   0,   0,  95, 
      0,   0,   4, 242, 144,  33, 
      0,   3,   0,   0,   0,   1, 
      0,   0,   0,  95,   0,   0, 
      4, 114, 144,  33,   0,   3, 
      0,   0,   0,   2,   0,   0, 
      0,  95,   0,   0,   4, 114, 
    144,  33,   0,   3,   0,   0, 
      0,   3,   0,   0,   0,  95, 
      0,   0,   4, 114, 144,  33, 
      0,   3,   0,   0,   0,   4, 
      0,   0,   0,  95,   0,   0, 
      4, 114, 144,  33,   0,   3, 
      0,   0,   0,   5,   0,   0, 
      0,  95,   0,   0,   4, 114, 
    144,  33,   0,   3,   0,   0, 
      0,   6,   0,   0,   0, 101, 
      0,   0,   3, 242,  32,  16, 
      0,   0,   0,   0,   0, 101, 
      0,   0,   3, 242,  32,  16, 
      0,   1,   0,   0,   0, 101, 
      0,   0,   3, 114,  32,  16, 
      0,   2,   0,   0,   0, 101, 
      0,   0,   3, 114,  32,  16, 
      0,   3,   0,   0,   0, 101, 
      0,   0,   3, 114,  32,  16, 
      0,   4,   0,   0,   0, 101, 
      0,   0,   3, 114,  32,  16, 
      0,   5,   0,   0,   0, 103, 
      0,   0,   4, 242,  32,  16, 
      0,   6,   0,   0,   0,   1, 
      0,   0,   0, 104,   0,   0, 
      2,   2,   0,   0,   0,  56, 
      0,   0,   7, 242,   0,  16, 
      0,   0,   0,   0,   0,  86, 
    197,   1,   0,  70, 158,  33, 
      0,   1,   0,   0,   0,   0, 
      0,   0,   0,  50,   0,   0, 
      9, 242,   0,  16,   0,   0, 
      0,   0,   0,   6, 192,   1, 
      0,  70, 158,  33,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,  70,  14,  16,   0,   0, 
      0,   0,   0,  50,   0,   0, 
      9, 242,  32,  16,   0,   0, 
      0,   0,   0, 166, 202,   1, 
      0,  70, 158,  33,   0,   2, 
      0,   0,   0,   0,   0,   0, 
      0,  70,  14,  16,   0,   0, 
      0,   0,   0,  56,   0,   0, 
      7, 242,   0,  16,   0,   0, 
      0,   0,   0,  86, 197,   1, 
      0,  70, 158,  33,   0,   1, 
      0,   0,   0,   1,   0,   0, 
      0,  50,   0,   0,   9, 242, 
      0,  16,   0,   0,   0,   0, 
      0,   6, 192,   1,   0,  70, 
    158,  33,   0,   0,   0,   0, 
      0,   1,   0,   0,   0,  70, 
     14,  16,   0,   0,   0,   0, 
      0,  50,   0,   0,   9, 242, 
     32,  16,   0,   1,   0,   0, 
      0, 166, 202,   1,   0,  70, 
    158,  33,   0,   2,   0,   0, 
      0,   1,   0,   0,   0,  70, 
     14,  16,   0,   0,   0,   0, 
      0,  56,   0,   0,   7, 114, 
      0,  16,   0,   0,   0,   0, 
      0,  86, 197,   1,   0,  70, 
    146,  33,   0,   1,   0,   0, 
      0,   2,   0,   0,   0,  50, 
      0,   0,   9, 114,   0,  16, 
      0,   0,   0,   0,   0,   6, 
    192,   1,   0,  70, 146,  33, 
      0,   0,   0,   0,   0,   2, 
      0,   0,   0,  70,   2,  16, 
      0,   0,   0,   0,   0,  50, 
      0,   0,   9, 114,  32,  16, 
      0,   2,   0,   0,   0, 166, 
    202,   1,   0,  70, 146,  33, 
      0,   2,   0,   0,   0,   2, 
      0,   0,   0,  70,   2,  16, 
      0,   0,   0,   0,   0,  56, 
      0,   0,   7, 114,   0,  16, 
      0,   0,   0,   0,   0,  86, 
    197,   1,   0,  70, 146,  33, 
      0,   1,   0,   0,   0,   3, 
      0,   0,   0,  50,   0,   0, 
      9, 114,   0,  16,   0,   0, 
      0,   0,   0,   6, 192,   1, 
      0,  70, 146,  33,   0,   0, 
      0,   0,   0,   3,   0,   0, 
      0,  70,   2,  16,   0,   0, 
      0,   0,   0,  50,   0,   0, 
      9, 114,  32,  16,   0,   3, 
      0,   0,   0, 166, 202,   1, 
      0,  70, 146,  33,   0,   2, 
      0,   0,   0,   3,   0,   0, 
      0,  70,   2,  16,   0,   0, 
      0,   0,   0,  56,   0,   0, 
      7, 114,   0,  16,   0,   0, 
      0,   0,   0,  86, 197,   1, 
      0,  70, 146,  33,   0,   1, 
      0,   0,   0,   4,   0,   0, 
      0,  50,   0,   0,   9, 114, 
      0,  16,   0,   0,   0,   0, 
      0,   6, 192,   1,   0,  70, 
    146,  33,   0,   0,   0,   0, 
      0,   4,   0,   0,   0,  70, 
      2,  16,   0,   0,   0,   0, 
      0,  50,   0,   0,   9, 114, 
     32,  16,   0,   4,   0,   0, 
      0, 166, 202,   1,   0,  70, 
    146,  33,   0,   2,   0,   0, 
      0,   4,   0,   0,   0,  70, 
      2,  16,   0,   0,   0,   0, 
      0,  56,   0,   0,   7, 114, 
      0,  16,   0,   0,   0,   0, 
      0,  86, 197,   1,   0,  70, 
    146,  33,   0,   1,   0,   0, 
      0,   5,   0,   0,   0,  50, 
      0,   0,   9, 114,   0,  16, 
      0,   0,   0,   0,   0,   6, 
    192,   1,   0,  70, 146,  33, 
      0,   0,   0,   0,   0,   5, 
      0,   0,   0,  70,   2,  16, 
      0,   0,   0,   0,   0,  50, 
      0,   0,   9, 114,  32,  16, 
      0,   5,   0,   0,   0, 166, 
    202,   1,   0,  70, 146,  33, 
      0,   2,   0,   0,   0,   5, 
      0,   0,   0,  70,   2,  16, 
      0,   0,   0,   0,   0,  56, 
      0,   0,   7, 114,   0,  16, 
      0,   0,   0,   0,   0,  86, 
    197,   1,   0,  70, 146,  33, 
      0,   1,   0,   0,   0,   6, 
      0,   0,   0,  50,   0,   0, 
      9, 114,   0,  16,   0,   0, 
      0,   0,   0,   6, 192,   1, 
      0,  70, 146,  33,   0,   0, 
      0,   0,   0,   6,   0,   0, 
      0,  70,   2,  16,   0,   0, 
      0,   0,   0,  50,   0,   0, 
      9, 114,   0,  16,   0,   0, 
      0,   0,   0, 166, 202,   1, 
      0,  70, 146,  33,   0,   2, 
      0,   0,   0,   6,   0,   0, 
      0,  70,   2,  16,   0,   0, 
      0,   0,   0,  56,   0,   0, 
      8, 242,   0,  16,   0,   1, 
      0,   0,   0,  86,   5,  16, 
      0,   0,   0,   0,   0,  70, 
    142,  32,   0,   0,   0,   0, 
      0,  10,   0,   0,   0,  50, 
      0,   0,  10, 242,   0,  16, 
      0,   1,   0,   0,   0,  70, 
    142,  32,   0,   0,   0,   0, 
      0,   9,   0,   0,   0,   6, 
      0,  16,   0,   0,   0,   0, 
      0,  70,  14,  16,   0,   1, 
      0,   0,   0,  50,   0,   0, 
     10, 242,   0,  16,   0,   0, 
      0,   0,   0,  70, 142,  32, 
      0,   0,   0,   0,   0,  11, 
      0,   0,   0, 166,  10,  16, 
      0,   0,   0,   0,   0,  70, 
     14,  16,   0,   1,   0,   0, 
      0,   0,   0,   0,   8, 242, 
     32,  16,   0,   6,   0,   0, 
      0,  70,  14,  16,   0,   0, 
      0,   0,   0,  70, 142,  32, 
      0,   0,   0,   0,   0,  12, 
      0,   0,   0,  62,   0,   0, 
      1,  83,  84,  65,  84, 148, 
      0,   0,   0,  26,   0,   0, 
      0,   2,   0,   0,   0,   0, 
      0,   0,   0,  15,   0,   0, 
      0,   9,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   1,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   1,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   3,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   2,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0, 169,  24,   0,   0,   0, 
      0,   0,   0, 208,   1,   0, 
      0,  68,  88,  66,  67, 249, 
     23, 206,  58, 142, 253,  97, 
    177, 121, 104, 240,  70,  57, 
     87, 218,  93,   1,   0,   0, 
      0, 208,   1,   0,   0,   5, 
      0,   0,   0,  52,   0,   0, 
      0, 172,   0,   0,   0, 188, 
      0,   0,   0, 240,   0,   0, 
      0,  52,   1,   0,   0,  82, 
     68,  69,  70, 112,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,  60,   0,   0,   0,   0, 
      5, 255, 255,   0,   1,   0, 
      0,  60,   0,   0,   0,  82, 
     68,  49,  49,  60,   0,   0, 
      0,  24,   0,   0,   0,  32, 
      0,   0,   0,  40,   0,   0, 
      0,  36,   0,   0,   0,  12, 
      0,   0,   0,   0,   0,   0, 
      0,  77, 105,  99, 114, 111, 
    115, 111, 102, 116,  32,  40, 
     82,  41,  32,  72,  76,  83, 
     76,  32,  83, 104,  97, 100, 
    101, 114,  32,  67, 111, 109, 
    112, 105, 108, 101, 114,  32, 
     57,  46,  51,  48,  46,  57, 
     50,  48,  48,  46,  49,  54, 
     51,  56,  52,   0, 171,  73, 
     83,  71,  78,   8,   0,   0, 
      0,   0,   0,   0,   0,   8, 
      0,   0,   0,  79,  83,  71, 
     78,  44,   0,   0,   0,   1, 
      0,   0,   0,   8,   0,   0, 
      0,  32,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   3,   0,   0,   0,   0, 
      0,   0,   0,  15,   0,   0, 
      0,  83,  86,  95,  84,  65, 
     82,  71,  69,  84,   0, 171, 
    171,  83,  72,  69,  88,  60, 
      0,   0,   0,  80,   0,   0, 
      0,  15,   0,   0,   0, 106, 
      8,   0,   1, 101,   0,   0, 
      3, 242,  32,  16,   0,   0, 
      0,   0,   0,  54,   0,   0, 
      8, 242,  32,  16,   0,   0, 
      0,   0,   0,   2,  64,   0, 
      0,   0,   0, 128,  63,   0, 
      0, 128,  63,   0,   0, 128, 
     63,   0,   0, 128,  63,  62, 
      0,   0,   1,  83,  84,  65, 
     84, 148,   0,   0,   0,   2, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   1, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   1,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   2,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   1,  35,   0, 
      0,   0,   0,   0,   0,   4, 
      0,   0,   0,  32,   1,   0, 
      0,   0,   0,   0,   0,   7, 
      0,   0,   0, 255, 255, 255, 
    255,   0,   0,   0,   0,  48, 
      0,   0,   0,  20,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0, 107,   0,   0, 
      0,  79,   0,   0,   0, 115, 
      0,   0,   0,  16,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0, 121,   0,   0,   0,  79, 
      0,   0,   0, 126,   0,   0, 
      0,  80,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0, 141, 
      0,   0,   0,  79,   0,   0, 
      0, 147,   0,   0,   0, 144, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0, 167,   0,   0, 
      0,  79,   0,   0,   0,   0, 
      0,   0,   0, 208,   0,   0, 
      0, 181,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,  23,   1,   0,   0, 251, 
      0,   0,   0,   0,   0,   0, 
      0,  16,   1,   0,   0,  34, 
      1,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,  38, 
      1,   0,   0, 251,   0,   0, 
      0,  53,   1,   0,   0,  20, 
      1,   0,   0,  66,   1,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   1,   0,   0,   0,   0, 
      0,   0,   0,  70,   1,   0, 
      0,   2,   0,   0,   0,   0, 
      0,   0,   0,  78,   1,   0, 
      0,   2,   0,   0,   0,   0, 
      0,   0,   0,   6,   0,   0, 
      0,   0,   0,   0,   0,   7, 
      0,   0,   0,  35,   7,   0, 
      0,   7,   0,   0,   0,   0, 
      0,   0,   0,   7,   0,   0, 
      0, 255,   8,   0,   0,   7, 
      9,   0,   0,   4,   0,   0, 
      0,   0,   0,   0,   0,   6, 
      0,   0,   0,   0,   0,   0, 
      0,   7,   0,   0,   0, 177, 
     17,   0,   0,  56,   0,   0, 
      0,   0,   0,   0,   0,   7, 
      0,   0,   0, 161,  24,   0, 
      0,  57,   0,   0,   0,   0, 
      0,   0,   0,   7,   0,   0, 
      0, 249,  34,   0,   0,   7, 
      0,   0,   0,   0,   0,   0, 
      0,   7,   0,   0,   0, 213, 
     36,   0,   0
};
