/*****************************************************************************
**	eonGeomExporter.hpp
**
**		Utilities for exporting geometry files to EON Reality file format
**
**	Extra Large Technology
**	Copyright(C) 2008 - All Rights Reserved
\****************************************************************************/
#ifdef EON_GEOMEXPORTER_HPP
#error eonGeomExporter.hpp multiply included
#endif
#define EON_GEOMEXPORTER_HPP

#ifndef MNM_CONSTANTS_HPP
#include "Support/mnm/mnmConstants.hpp"
#endif 
#ifndef ENV_BOOST_HPP
#include "Core/Env/envBoost.hpp"
#endif 

#include <map>
#include <vector>

//============================================================================
//	forward references
//============================================================================
class chWriter;
class fsLocator;
class g3dFragment;
class mdlMaterialInfo;

//============================================================================
//============================================================================
#ifdef EON_REALITY
namespace eonGeomExporter
{
	//------------------------------------------------------------------------
	//  ConvertToEON() - read the given MachStudio Maya exported file
	//		and export to EON, setting up materials to match the
	//		names generated by the baked textures.
	//------------------------------------------------------------------------
	void  ConvertToEON(const fsLocator& i_MachFile,
						chWriter& o_Writer,
						const std::vector< shared_ptr<mdlMaterialInfo> >& i_MaterialOverrides,
						const std::vector<g3dFragment*>& i_Fragments,
						std::map<const g3dFragment*, std::string> &i_TextureNameMap,
						bool i_bRelativeTextureNames);
}
#endif // EON_REALITY
