
;--------------------------------
;Include Modern UI

  !include "MUI2.nsh"
	
;--------------------------------
; Script generated by the HM NIS Edit Script Wizard.

  !include LogicLib.nsh
  !include WordFunc.nsh

  !include IfKeyExists.nsh
  !include WinVer.nsh
	
;--------------------------------
	;!include "EnumUsersReg.nsh"
	!include "FileFunc.nsh"


;--------------------------------
; macros

  !insertmacro VersionCompare
  
  !insertmacro GetParameters
  !insertmacro GetOptions
  !insertmacro un.GetParameters
  !insertmacro un.GetOptions
	
	!insertmacro un.DirState
	

;--------------------------------
  ;Request application privileges for Windows Vista

  RequestExecutionLevel admin

;--------------------------------
;General

  ;Name and file
  Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
  ;OutFile "Output\${PRODUCT_INAME}_setup_${PRODUCT_VERSIONNS}.exe"
  OutFile "Output\${PRODUCT_INAME}_setup.exe"
  ;Default installation folder
!ifdef WINDOWS_X64
	InstallDir "$PROGRAMFILES64\${PRODUCT_PUBLISHER}\${PRODUCT_LNAME}"
	!include x64.nsh
!else
  InstallDir "$PROGRAMFILES\${PRODUCT_PUBLISHER}\${PRODUCT_LNAME}"
!endif
  
  ;Get installation folder from registry if available
  InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""

  ;show    hide
  ShowInstDetails nevershow
  ShowUnInstDetails nevershow


;--------------------------------
;Things that need to be extracted on startup (keep these lines before any File command!)
;Only useful for BZIP2 compression
;Use ReserveFile for your own InstallOptions INI files too!

ReserveFile "${NSISDIR}\Plugins\InstallOptions.dll"

;--------------------------------
;Variables

  Var StartMenuFolder

;--------------------------------
;Interface Settings

  !define MUI_ICON "${PRODUCT_INAME_BASE}.ico"
  !define MUI_HEADERIMAGE
  !define MUI_HEADERIMAGE_BITMAP "${NSISDIR}\Contrib\Graphics\Header\win.bmp" ; optional
  !define MUI_ABORTWARNING

;--------------------------------
;Pages

  ;Page custom PageReinstall PageLeaveReinstall
	
  ;!insertmacro MULTIUSER_PAGE_INSTALLMODE

  ;!insertmacro MUI_PAGE_LICENSE "${NSISDIR}\Docs\Modern UI\License.txt"
  ;!insertmacro MUI_PAGE_COMPONENTS
  !insertmacro MUI_PAGE_DIRECTORY

  ;Start Menu Folder Page Configuration
  !define MUI_STARTMENUPAGE_REGISTRY_ROOT "HKLM" 
  !define MUI_STARTMENUPAGE_REGISTRY_KEY "Software\${PRODUCT_PUBLISHER}\${PRODUCT_INAME}\Install"
  !define MUI_STARTMENUPAGE_REGISTRY_VALUENAME "Start Menu Folder"
  
	!define MUI_STARTMENUPAGE_DEFAULTFOLDER "${PRODUCT_PUBLISHER}\${PRODUCT_LNAME}"
	
  !insertmacro MUI_PAGE_STARTMENU Application $StartMenuFolder
  
  !insertmacro MUI_PAGE_INSTFILES
  
  !insertmacro MUI_UNPAGE_CONFIRM
  !insertmacro MUI_UNPAGE_INSTFILES
  !insertmacro MUI_UNPAGE_FINISH

;--------------------------------
;Languages
 
  !insertmacro MUI_LANGUAGE "English"

Var PREVIOUS_INSTALLDIR
Var PREVIOUS_VERSION
Var REINSTALL_UNINSTALL
Var REINSTALL_UNINSTALLBUTTON
Var PREVIOUS_VERSION_STATE
Var UNINSTALL_STATE

;--------------------------------
; Page Reinstall

Function CheckReinstall

  ReadRegStr $PREVIOUS_INSTALLDIR HKLM "${PRODUCT_DIR_REGKEY}" ""

  ${If} $PREVIOUS_INSTALLDIR == ""
    Goto lbl_skip
  ${EndIf}
  
  MessageBox MB_ICONEXCLAMATION|MB_YESNO "${PRODUCT_NAME} is already installed. Deinstall it?" IDYES lbl_reinstall IDNO lbl_exit
  
  lbl_reinstall:
    HideWindow
    Call RunUninstaller
    Goto lbl_skip
     
  lbl_exit:
    Abort
  
  lbl_skip:

FunctionEnd

Function RunUninstaller

  ReadRegStr $1 ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString"

  IfFileExists "$1" 0 no_remove_uninstaller
  ;ExecWait "$1 /nocheckrun /noquestions"
  ExecWait '$1 /nocheckrun /noquestions /S _?=$INSTDIR' $2

  ;MessageBox MB_ICONQUESTION|MB_OK "$2"
  ${If} $2 == 1
    Abort
  ${EndIf}
  
  no_remove_uninstaller:

FunctionEnd


;--------------------------------
;Installer Sections

!include "${PRODUCT_INAME_BASE}_Files.nsh"


Section -AdditionalIcons
  SetOutPath $INSTDIR
  CreateShortCut "$SMPROGRAMS\$StartMenuFolder\Uninstall.lnk" "$INSTDIR\uninst.exe"
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\${PRODUCT_INAME}.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\${PRODUCT_INAME}.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd

;--------------------------------
;Descriptions

  ;Language strings
  LangString DESC_SecDummy ${LANG_ENGLISH} "A test section."

  ;Assign language strings to sections
  !insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN
  !insertmacro MUI_DESCRIPTION_TEXT ${SecDummy} $(DESC_SecDummy)
  !insertmacro MUI_FUNCTION_DESCRIPTION_END
 
;--------------------------------

Function CheckPluginRun

  TryAgain:

  ; Call the Win32 API to create the mutex. Pass a unique string (ie. product name)
  System::Call 'kernel32::CreateMutexA(i 0, i 0, t "${PRODUCT_MUTEX}") i .r1 ?e'
  Pop $R0 ; Get the mutex handle
  
  StrCmp $R0 0 noprevinst
	
	System::Call 'kernel32::CloseHandle(i r1) i .r2' ; Free Mutex to check again

  Messagebox MB_OKCancel "${PRODUCT_NAME} is runing. Please, close programm and click 'OK'" IDOK TryAgain
  Abort

  noprevinst:
  
FunctionEnd

Function CheckWindowsVersion

!ifdef WINDOWS_X64
	
	GetVersion::WindowsPlatformArchitecture
  Pop $R0
	
	IntCmp $R0 64 lbl_ok_64
	
	MessageBox MB_OK|MB_ICONSTOP   "System Requirements: x64 Windows OS (You use $R0 bit OS)" IDOK
	Abort
	
	lbl_ok_64:
	
!else

  GetVersion::WindowsName
  Pop $R0
  
  GetVersion::WindowsServicePack
  Pop $R1
  
/*GetVersion::WindowsType
  Pop $R0

 GetVersion::WindowsVersion
  Pop $R0

 GetVersion::WindowsServerName
  Pop $R0

 GetVersion::WindowsPlatformId
  Pop $R0

 GetVersion::WindowsPlatformArchitecture
  Pop $R0
*/
  
  StrCmp $R0 'Vista' lbl_done
  StrCmp $R0 'Server Longhorn' lbl_done
  StrCmp $R0 'Server 2003' lbl_done
  StrCmp $R0 'Server 2003 R2' lbl_done
  StrCmp $R0 'XP x64' lbl_done

  StrCmp $R0 'XP' lbl_win_XP

  StrCmp $R0 '2000' lbl_abort
  StrCmp $R0 'CE' lbl_abort
  StrCmp $R0 'NT' lbl_abort
  StrCmp $R0 'ME' lbl_abort
  StrCmp $R0 '98' lbl_abort
  StrCmp $R0 '98 SE' lbl_abort
  StrCmp $R0 '95' lbl_abort
  StrCmp $R0 '95 OSR2' lbl_abort
  StrCmp $R0 'Win32s' lbl_abort

 lbl_win_XP:
   StrCmp $R1 'Windows XP Gold/SP0' lbl_abort
   StrCmp $R1 'Service Pack 1' lbl_abort
   StrCmp $R1 'Service Pack 2' lbl_done
   StrCmp $R1 'Service Pack 3' lbl_done

  lbl_abort:
    MessageBox MB_OK|MB_ICONSTOP   "System Requirements: Windows XP SP2 and higher. You use: Windows $R0 $R1" IDOK
    Abort
    
  lbl_done:
    ;MessageBox MB_OK|MB_ICONQUESTION   "You use: $R0 $R1" IDOK

!endif

FunctionEnd


Function .onInit
	
	Call CheckWindowsVersion
	
!ifdef WINDOWS_X64
	${EnableX64FSRedirection}
	SetRegView 64
!endif
	
!ifdef CUSTOMINIT
	Call CustomInit
!endif

  Call CheckPluginRun
  Call CheckReinstall
  
  
FunctionEnd

;--------------------------------
; Uninstaller

Var option_noQuestions
Var option_noCheckMe2Run

Function un.onInit

!ifdef WINDOWS_X64
	${EnableX64FSRedirection}
	SetRegView 64
!endif


  Call un.IsTempInstall

  ${If} $option_noCheckMe2Run == 0
    Call un.CheckPluginRun
    
    MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "Really delete $(^Name) and all its components?" IDYES +2
    Abort
  ${EndIf}

FunctionEnd

Function un.IsTempInstall

  ; Get parameters

  var /GLOBAL cmdLineParams
  Push $R0

  ${un.GetParameters} $cmdLineParams

  ; /? param (help)
  ClearErrors
  ${un.GetOptions} $cmdLineParams '/?' $R0
  IfErrors +3 0
  MessageBox MB_OK "list all command line options here!"
  Abort

  Pop $R0

  ; Initialise options
  StrCpy $option_noQuestions     0
  StrCpy $option_noCheckMe2Run   0

  ; Parse Parameters
  Push $R0
    ; /norun
    ${un.GetOptions} $cmdLineParams '/noquestions' $R0
    IfErrors +2 0
    StrCpy $option_noQuestions 1

    ; /nostartmenu
    ${un.GetOptions} $cmdLineParams '/nocheckrun' $R0
    IfErrors +2 0
    StrCpy $option_noCheckMe2Run 1
  Pop $R0

  ;MessageBox MB_OK "[$cmdLineParams]"
  ;MessageBox MB_OK "[$option_noQuestions]"
  ;MessageBox MB_OK "[$option_noCheckMe2Run]"

FunctionEnd


Function un.CheckPluginRun

  TryAgain:

  ; Call the Win32 API to create the mutex. Pass a unique string (ie. product name)
  System::Call 'kernel32::CreateMutexA(i 0, i 0, t "${PRODUCT_MUTEX}") i .r1 ?e'
  Pop $R0 ; Get the mutex handle
  
  StrCmp $R0 0 noprevinst
	
	System::Call 'kernel32::CloseHandle(i r1) i .r2' ; Free Mutex to check again

  Messagebox MB_OKCancel "${PRODUCT_NAME} is runing. Please, close programm and click 'OK'" IDOK TryAgain
  Abort

  noprevinst:

FunctionEnd

LangString PAGE_TITLE_UN ${LANG_ENGLISH} "Uninstal ${PRODUCT_NAME}"
LangString PAGE_SUBTITLE_UN ${LANG_ENGLISH} "Really delete $(^Name) and all its components?"

;--------------------------------
;Uninstaller Section

Section Uninstall

  ; for Vista
  ; SetShellVarContext all
  
  !insertmacro MUI_STARTMENU_GETFOLDER Application $StartMenuFolder
  
	!include "${PRODUCT_INAME_BASE}_UnFiles.nsh"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
	
	DeleteRegKey HKLM "Software\${PRODUCT_PUBLISHER}\${PRODUCT_INAME}\Install"

  SetAutoClose true
  
SectionEnd
