/*****************************************************************************
**	g3dPrimitiveFragmentUtil.hpp
**
**		The g3dPrimitiveFragmentUtil component contains some helpful functions
**	to make fragments which are common shapes.  All shapes generated by the
**	g3dPrimitiveFragmentUtil use the g3dPrimitiveFragmentUtil::DefaultMaterial
**	and are centered at the origin of their coordinate system.  Of course,
**	materials for these fragments can be changed later using the
**	g3dFragmentManager.
**		When you are done with one of these fragments you should destroy it
**	with the g3dFragmentManager::Destroy function.
**
**	StudioGPU
**	Copyright(C) 2003 - All Rights Reserved
\****************************************************************************/
#ifdef G3D_PRIMITIVEFRAGMENTUTIL_HPP
#error g3dPrimitiveFragmentUtil.hpp multiply included
#endif
#define G3D_PRIMITIVEFRAGMENTUTIL_HPP

#ifndef MA_POINT3D_HPP
#include "Core/ma/maPoint3d.hpp"
#endif


//============================================================================
//	Forward References
//============================================================================
class g3dFragment;
class matMaterial;


//============================================================================
//============================================================================
namespace g3dPrimitiveFragmentUtil
{
		//--------------------------------------------------------------------
		//	CreateCube makes a fragment which is a cube with sides of the
		//	given length.
		//--------------------------------------------------------------------
		g3dFragment* CreateCube( float i_fSide, bool i_bMorphable = false);

		//--------------------------------------------------------------------
		//	CreateTexturedCube makes a cube which has texture coordinates
		//	assigned.
		//--------------------------------------------------------------------
		g3dFragment* CreateTexturedCube( float i_fSide );

		//--------------------------------------------------------------------
		//	CreateLineCube makes a cube drawn with lines for the edges.
		//--------------------------------------------------------------------
		g3dFragment* CreateLineCube( float i_fSide );

		//--------------------------------------------------------------------
		//	CreateBlock makes a fragment which is a block with sides of the
		//	given lengths.
		//--------------------------------------------------------------------
		g3dFragment* CreateBlock( float i_fXSide, float i_fYSide, float i_fZSide );

		//--------------------------------------------------------------------
		//	CreateTexturedCube makes a block which has texture coordinates
		//	assigned.
		//--------------------------------------------------------------------
		g3dFragment* CreateTexturedBlock( float i_fXSide, float i_fYSide, float i_fZSide );

		//--------------------------------------------------------------------
		//	CreateLineBlock makes a fragment which is a block with sides of the
		//	given lengths, drawn with lines.
		//--------------------------------------------------------------------
		g3dFragment* CreateLineBlock( float i_fXSide, float i_fYSide, float i_fZSide, bool i_bMorphable = false );

		//--------------------------------------------------------------------
		//	CreateSphere makes a sphere-like object which has the given radius,
		//	latitude divisions, and longitude divisions.
		//--------------------------------------------------------------------
		g3dFragment* CreateSphere( float i_fRadius, int i_nLatDiv, int i_nLongDiv );

		//--------------------------------------------------------------------
		//	CreateTexturedSphere makes a sphere-like object which has texture
		//	coordinates.
		//--------------------------------------------------------------------
		g3dFragment* CreateTexturedSphere( float i_fRadius, int i_nLatDiv, int i_nLongDiv );

		//--------------------------------------------------------------------
		//	CreateReverseTexturedSphere makes a texture sphere-like object
		//	which triangles and normals facing inward.
		//--------------------------------------------------------------------
		g3dFragment* CreateReverseTexturedSphere( float i_fRadius, int i_nLatDiv, int i_nLongDiv );

		//--------------------------------------------------------------------
		//	CreateCone makes a cone-like object which has the given base radius,
		//	height, and divisions.
		//--------------------------------------------------------------------
		g3dFragment* CreateCone( float i_fBaseRadius, float i_fHeight, int i_nDivisions);

		//--------------------------------------------------------------------
		//	CreateCylinder makes a cylinder-like object which has the given radius,
		//	height, and divisions.
		//--------------------------------------------------------------------
		g3dFragment* CreateCylinder( float i_Radius, float i_BottomRadius, float i_Height, int i_Divisions );

		//--------------------------------------------------------------------
		//	CreateRectangle creates a subdivided rectangle.  The rectangle
		//	faces towards positive Z and is centered at the origin.
		//--------------------------------------------------------------------
		g3dFragment* CreateRectangle(	float i_fWidth,
										float i_fHeight,
										int i_nWidthDivisions,
										int i_nHeightDivisions,
										bool i_bMorphable = false);

		//--------------------------------------------------------------------
		//	CreateTexturedRectangle creates a subdivided rectangle with
		//	texture coordinates.  The rectangle faces towards
		//	positive Z and is centered at the origin.
		//--------------------------------------------------------------------
		g3dFragment* CreateTexturedRectangle(	float i_fWidth,
												float i_fHeight,
												int i_nWidthDivisions,
												int i_nHeightDivisions,
												//int i_nNumTextures = 1,
												bool i_bMorphable = false);

		//--------------------------------------------------------------------
		//	CreateCircle makes a circle line object around the y-axis with the given
		//	radius.  The arc is drawn between the start and end radians.
		//--------------------------------------------------------------------
		g3dFragment* CreateCircle( float i_fRadius, int i_nDivisions );


		//--------------------------------------------------------------------
		//	CreateIsoscelesTriangle makes an isosceles triangle (a triangle
		//  with two equal sides).
		//--------------------------------------------------------------------
		g3dFragment* CreateIsoscelesTriangle( float i_fBase, float i_fHeight );

		//--------------------------------------------------------------------
		//	CreateEquilateralTriangle makes an equilateral triangle (a
		//  triangle with three equal sides).
		//--------------------------------------------------------------------
		g3dFragment* CreateEquilateralTriangle( float i_fSide );

		//--------------------------------------------------------------------
		//	CreateLine makes a line from point 1 to point 2
		//--------------------------------------------------------------------
		g3dFragment* CreateLine( const maPoint3d& i_Point1, const maPoint3d& i_Point2 );

		//--------------------------------------------------------------------
		//	CreateSpline makes a line list fragment from the spline
		//--------------------------------------------------------------------
		//g3dFragment* CreateSpline( const geoSpline& i_Spline );

		//--------------------------------------------------------------------
		//	DefaultMaterial returns the default material which is used by the
		//	fragments created by the g3dPrimitiveFragmentUtil.  It can be
		//	modified by the client.
		//--------------------------------------------------------------------
		matMaterial& DefaultMaterial();
}
