/*****************************************************************************
**  inKeys.cpp
**
**      inKeys defines a namespace inKeys to hold an enumeration of terawatt
**		keys.
**
**	StudioGPU
**	Copyright(C) 2003 - All Rights Reserved
\****************************************************************************/

#include "Input/in/inKeys.hpp"

namespace inKeys
{

itString TerawattKeyStrings[e_NUMTERAWATTKEYS] = {
	itString("A"),
	itString("B"),
	itString("C"),
	itString("D"),
	itString("E"),
	itString("F"),
	itString("G"),
	itString("H"),
	itString("I"),
	itString("J"),
	itString("K"),
	itString("L"),
	itString("M"),
	itString("N"),
	itString("O"),
	itString("P"),
	itString("Q"),
	itString("R"),
	itString("S"),
	itString("T"),
	itString("U"),
	itString("V"),
	itString("W"),
	itString("X"),
	itString("Y"),
	itString("Z"),
	itString("0"),
	itString("1"),
	itString("2"),
	itString("3"),
	itString("4"),
	itString("5"),
	itString("6"),
	itString("7"),
	itString("8"),
	itString("9"),
	itString("ESC"),
	itString("F1"),
	itString("F2"),
	itString("F3"),
	itString("F4"),
	itString("F5"),
	itString("F6"),
	itString("F7"),
	itString("F8"),
	itString("F9"),
	itString("F10"),
	itString("F11"),
	itString("F12"),
	itString("PRINT"),
	itString("SCROLL"),
	itString("PAUSE"),
	itString("TILDE"),
	itString("DASH"),
	itString("EQUALS"),
	itString("BACKSPACE"),
	itString("TAB"),
	itString("LBRACKET"),
	itString("RBRACKET"),
	itString("BACKSLASH"),
	itString("CAPSLOCK"),
	itString("SEMICOLON"),
	itString("APOSTROPHE"),
	itString("ENTER"),
	itString("LSHIFT"),
	itString("COMMA"),
	itString("PERIOD"),
	itString("SLASH"),
	itString("RSHIFT"),
	itString("LCTRL"),
	itString("LWIN"),
	itString("LALT"),
	itString("SPACE"),
	itString("RALT"),
	itString("RWIN"),
	itString("RCTRL"),
	itString("INSERT"),
	itString("HOME"),
	itString("PAGEUP"),
	itString("DELETE"),
	itString("END"),
	itString("PAGEDOWN"),
	itString("UP"),
	itString("DOWN"),
	itString("LEFT"),
	itString("RIGHT"),
	itString("NUMPAD0"),
	itString("NUMPAD1"),
	itString("NUMPAD2"),
	itString("NUMPAD3"),
	itString("NUMPAD4"),
	itString("NUMPAD5"),
	itString("NUMPAD6"),
	itString("NUMPAD7"),
	itString("NUMPAD8"),
	itString("NUMPAD9"),
	itString("NUMLOCK"),
	itString("NUMPADDIVIDE"),
	itString("NUMPADMULTIPLY"),
	itString("NUMPADMINUS"),
	itString("NUMPADPLUS"),
	itString("NUMPADDECIMAL"),
	itString("NUMPADENTER")
};

}